import type {
  Address,
  Client,
  ClientStatus,
  Contact,
  OnboardingItem,
  OnboardingStage,
  OnboardingStatus,
} from "@/types";

import { IDS } from "./ids";

const now = new Date().toISOString();
const tenantId = IDS.TENANT;
const fyStart = 4; // April

const baseEntity = {
  tenantId,
  createdAt: now,
  updatedAt: now,
  createdBy: IDS.USERS.ADMIN,
  updatedBy: IDS.USERS.ADMIN,
};

const defaultAddress: Address = {
  line1: "123 Business Park",
  line2: "Sector 44",
  city: "Gurugram",
  state: "Haryana",
  postalCode: "122003",
  country: "India",
};

const mumbaiAddress: Address = {
  line1: "456 Commercial Complex",
  line2: "Bandra Kurla Complex",
  city: "Mumbai",
  state: "Maharashtra",
  postalCode: "400051",
  country: "India",
};

const bangaloreAddress: Address = {
  line1: "789 Tech Park",
  line2: "Whitefield",
  city: "Bengaluru",
  state: "Karnataka",
  postalCode: "560066",
  country: "India",
};

const delhiAddress: Address = {
  line1: "321 Corporate Tower",
  line2: "Connaught Place",
  city: "New Delhi",
  state: "Delhi",
  postalCode: "110001",
  country: "India",
};

const createOnboardingStatus = (stage: OnboardingStatus["stage"], progress: number): OnboardingStatus => {
  const allStages: OnboardingStage[] = [
    "profile_created",
    "contacts_added",
    "identifiers_added",
    "services_configured",
    "kyc_documents_collected",
    "compliance_configured",
    "team_assigned",
    "initial_matters_created",
    "portal_invited",
  ];
  const stageIndex = allStages.indexOf(stage);
  return {
    stage,
    progress,
    completedStages: stageIndex >= 0 ? allStages.slice(0, stageIndex + 1) : [],
    pendingItems: [],
  };
};

const _onboardingItems: OnboardingItem[] = [
  {
    id: "1",
    stage: "profile_created",
    title: "Create Client Profile",
    description: "Basic client information and legal entity details",
    isCompleted: true,
    completedAt: now,
    completedBy: IDS.USERS.ADMIN,
  },
  {
    id: "2",
    stage: "contacts_added",
    title: "Add Key Contacts",
    description: "Primary contact, authorized signatories, and communication preferences",
    isCompleted: true,
    completedAt: now,
    completedBy: IDS.USERS.ADMIN,
  },
  {
    id: "3",
    stage: "identifiers_added",
    title: "Record Identifiers",
    description: "PAN, TAN, GSTIN, CIN, DIN and other regulatory identifiers",
    isCompleted: true,
    completedAt: now,
    completedBy: IDS.USERS.ADMIN,
  },
  {
    id: "4",
    stage: "services_configured",
    title: "Configure Services",
    description: "Select and configure active services with billing and compliance settings",
    isCompleted: true,
    completedAt: now,
    completedBy: IDS.USERS.ADMIN,
  },
  {
    id: "5",
    stage: "kyc_documents_collected",
    title: "Collect KYC Documents",
    description: "PAN, Aadhaar, incorporation certificate, MOA/AOA, partnership deed",
    isCompleted: false,
  },
  {
    id: "6",
    stage: "compliance_configured",
    title: "Configure Compliance",
    description: "Set up compliance calendar, due dates, and reminder schedules",
    isCompleted: false,
  },
  {
    id: "7",
    stage: "team_assigned",
    title: "Assign Team",
    description: "Assign responsible CA, team, and escalation matrix",
    isCompleted: false,
  },
  {
    id: "8",
    stage: "initial_matters_created",
    title: "Create Initial Matters",
    description: "Set up first compliance matters and work items",
    isCompleted: false,
  },
  {
    id: "9",
    stage: "portal_invited",
    title: "Invite to Client Portal",
    description: "Send portal invitation for document sharing and communication",
    isCompleted: false,
  },
];

export const mockClients: Client[] = [
  {
    ...baseEntity,
    id: IDS.CLIENTS.ABC_PVT_LTD,
    name: "ABC Private Limited",
    legalName: "ABC Private Limited",
    displayName: "ABC Pvt Ltd",
    type: "private_limited",
    category: "multi_service",
    status: "active",
    primaryContactId: IDS.CONTACTS.ABC_RAJESH,
    contacts: [],
    identifiers: {
      pan: "AABCA1234A",
      tan: "DELA12345A",
      gstin: "06AABCA1234A1Z5",
      cin: "U74999HR2020PTC012345",
      din: ["01234567", "07654321"],
      iec: "0512345678",
    },
    address: defaultAddress,
    billingAddress: defaultAddress,
    responsibleUserId: IDS.USERS.PARTNER_1,
    responsibleTeamId: IDS.TEAMS.TAXATION,
    services: [
      {
        ...baseEntity,
        id: "svc-abc-itr",
        clientId: IDS.CLIENTS.ABC_PVT_LTD,
        serviceType: "itr",
        serviceName: "Income Tax Return Filing",
        description: "Annual ITR filing for company",
        frequency: "annual",
        startDate: "2024-04-01",
        assignedUserId: IDS.USERS.SENIOR_1,
        assignedTeamId: IDS.TEAMS.TAXATION,
        billingMethod: "fixed_fee",
        rate: 50000,
        currency: "INR",
        isActive: true,
        complianceConfig: {
          applicableForms: ["ITR-6"],
          dueDateRule: { type: "fixed_date", value: 31, unit: "months", referenceDate: "2024-10-31" },
          documentRequirements: [
            { documentType: "financial_statements", isMandatory: true, dueBeforeFiling: true },
            { documentType: "tax_returns", isMandatory: true, dueBeforeFiling: true },
            { documentType: "form_26as", isMandatory: true, dueBeforeFiling: true },
          ],
        },
      },
      {
        ...baseEntity,
        id: "svc-abc-gst",
        clientId: IDS.CLIENTS.ABC_PVT_LTD,
        serviceType: "gst_monthly",
        serviceName: "GST Monthly Return Filing",
        description: "GSTR-1 and GSTR-3B monthly filing",
        frequency: "monthly",
        startDate: "2024-04-01",
        assignedUserId: IDS.USERS.SENIOR_1,
        assignedTeamId: IDS.TEAMS.GST,
        billingMethod: "fixed_fee",
        rate: 15000,
        currency: "INR",
        isActive: true,
        complianceConfig: {
          applicableForms: ["GSTR-1", "GSTR-3B"],
          dueDateRule: { type: "relative_to_period_end", value: 11, unit: "days" },
          documentRequirements: [
            { documentType: "invoices", isMandatory: true, dueBeforeFiling: true },
            { documentType: "bank_statements", isMandatory: false, dueBeforeFiling: false },
          ],
        },
      },
      {
        ...baseEntity,
        id: "svc-abc-tds",
        clientId: IDS.CLIENTS.ABC_PVT_LTD,
        serviceType: "tds_24q",
        serviceName: "TDS Return Filing (24Q)",
        description: "Quarterly TDS return for salary payments",
        frequency: "quarterly",
        startDate: "2024-04-01",
        assignedUserId: IDS.USERS.ASSOCIATE_1,
        assignedTeamId: IDS.TEAMS.TAXATION,
        billingMethod: "fixed_fee",
        rate: 8000,
        currency: "INR",
        isActive: true,
      },
      {
        ...baseEntity,
        id: "svc-abc-audit",
        clientId: IDS.CLIENTS.ABC_PVT_LTD,
        serviceType: "audit_statutory",
        serviceName: "Statutory Audit",
        description: "Annual statutory audit under Companies Act",
        frequency: "annual",
        startDate: "2024-04-01",
        assignedUserId: IDS.USERS.MANAGER_2,
        assignedTeamId: IDS.TEAMS.AUDIT,
        billingMethod: "fixed_fee",
        rate: 200000,
        currency: "INR",
        isActive: true,
      },
    ],
    complianceProfile: {
      applicableComplianceTypes: ["itr", "gst_monthly", "tds_24q", "audit_statutory"],
      financialYearStart: fyStart,
      gstFilingFrequency: "monthly",
      tdsApplicable: true,
      mcaApplicable: true,
      auditApplicable: true,
    },
    onboardingStatus: createOnboardingStatus("completed", 100),
    financialProfile: {
      annualTurnover: 150000000,
      taxableIncome: 25000000,
      gstLiability: 1800000,
      tdsLiability: 500000,
      outstandingReceivables: 1200000,
      outstandingPayables: 800000,
      creditLimit: 5000000,
      paymentTerms: 30,
      preferredPaymentMethod: "bank_transfer",
    },
    tags: ["manufacturing", "gst-regular", "audit-required"],
    notes: "Key manufacturing client. Requires monthly GST and annual audit.",
    portalAccessEnabled: true,
    portalInvitationSentAt: "2024-01-15T10:00:00Z",
  },
  {
    ...baseEntity,
    id: IDS.CLIENTS.XYZ_LLP,
    name: "XYZ LLP",
    legalName: "XYZ Limited Liability Partnership",
    displayName: "XYZ LLP",
    type: "llp",
    category: "taxation",
    status: "active",
    primaryContactId: IDS.CONTACTS.XYZ_AMIT,
    contacts: [],
    identifiers: {
      pan: "AABFX5678B",
      tan: "MUMX56789B",
      gstin: "27AABFX5678B1Z4",
      cin: "AAB-1234",
      din: [],
    },
    address: mumbaiAddress,
    billingAddress: mumbaiAddress,
    responsibleUserId: IDS.USERS.PARTNER_1,
    responsibleTeamId: IDS.TEAMS.TAXATION,
    services: [
      {
        ...baseEntity,
        id: "svc-xyz-itr",
        clientId: IDS.CLIENTS.XYZ_LLP,
        serviceType: "itr",
        serviceName: "ITR Filing for LLP",
        description: "Annual ITR-5 filing for LLP",
        frequency: "annual",
        startDate: "2024-04-01",
        assignedUserId: IDS.USERS.SENIOR_1,
        assignedTeamId: IDS.TEAMS.TAXATION,
        billingMethod: "fixed_fee",
        rate: 35000,
        currency: "INR",
        isActive: true,
      },
      {
        ...baseEntity,
        id: "svc-xyz-gst",
        clientId: IDS.CLIENTS.XYZ_LLP,
        serviceType: "gst_quarterly",
        serviceName: "GST Quarterly Return (QRMP)",
        description: "Quarterly GSTR-1 and monthly GSTR-3B under QRMP",
        frequency: "quarterly",
        startDate: "2024-04-01",
        assignedUserId: IDS.USERS.ASSOCIATE_1,
        assignedTeamId: IDS.TEAMS.GST,
        billingMethod: "fixed_fee",
        rate: 10000,
        currency: "INR",
        isActive: true,
      },
    ],
    complianceProfile: {
      applicableComplianceTypes: ["itr", "gst_quarterly"],
      financialYearStart: fyStart,
      gstFilingFrequency: "quarterly",
      tdsApplicable: false,
      mcaApplicable: false,
      auditApplicable: false,
    },
    onboardingStatus: createOnboardingStatus("completed", 100),
    financialProfile: {
      annualTurnover: 45000000,
      taxableIncome: 8000000,
      gstLiability: 540000,
      outstandingReceivables: 500000,
      outstandingPayables: 300000,
      paymentTerms: 45,
      preferredPaymentMethod: "upi",
    },
    tags: ["services", "gst-qrmp"],
    notes: "Service sector LLP under QRMP scheme.",
    portalAccessEnabled: true,
    portalInvitationSentAt: "2024-02-01T10:00:00Z",
  },
  {
    ...baseEntity,
    id: IDS.CLIENTS.SHARMA_PROP,
    name: "Sharma & Associates",
    legalName: "Sharma & Associates",
    displayName: "Sharma & Associates (Prop: Ravi Sharma)",
    type: "proprietorship",
    category: "taxation",
    status: "active",
    primaryContactId: IDS.CONTACTS.SHARMA_RAVI,
    contacts: [],
    identifiers: {
      pan: "BFPPS1234K",
      aadhaar: "1234-5678-9012",
      gstin: "07BFPPS1234K1Z3",
    },
    address: delhiAddress,
    billingAddress: delhiAddress,
    responsibleUserId: IDS.USERS.MANAGER_1,
    responsibleTeamId: IDS.TEAMS.TAXATION,
    services: [
      {
        ...baseEntity,
        id: "svc-sharma-itr",
        clientId: IDS.CLIENTS.SHARMA_PROP,
        serviceType: "itr",
        serviceName: "ITR Filing for Proprietorship",
        description: "ITR-3 filing for business income",
        frequency: "annual",
        startDate: "2024-04-01",
        assignedUserId: IDS.USERS.ASSOCIATE_1,
        assignedTeamId: IDS.TEAMS.TAXATION,
        billingMethod: "fixed_fee",
        rate: 15000,
        currency: "INR",
        isActive: true,
      },
    ],
    complianceProfile: {
      applicableComplianceTypes: ["itr"],
      financialYearStart: fyStart,
      tdsApplicable: false,
      mcaApplicable: false,
      auditApplicable: false,
    },
    onboardingStatus: createOnboardingStatus("kyc_documents_collected", 60),
    financialProfile: {
      annualTurnover: 8500000,
      taxableIncome: 1200000,
      outstandingReceivables: 200000,
      outstandingPayables: 100000,
      paymentTerms: 15,
      preferredPaymentMethod: "bank_transfer",
    },
    tags: ["proprietorship", "small-business"],
    notes: "Small proprietorship. ITR-3 filing only.",
    portalAccessEnabled: false,
  },
  {
    ...baseEntity,
    id: IDS.CLIENTS.GLOBAL_CORP,
    name: "Global Corporation India Pvt Ltd",
    legalName: "Global Corporation India Private Limited",
    displayName: "Global Corp India",
    type: "private_limited",
    category: "multi_service",
    status: "active",
    primaryContactId: IDS.CONTACTS.GLOBAL_SARAH,
    contacts: [],
    identifiers: {
      pan: "AACCG9876C",
      tan: "BLRG98765C",
      gstin: "29AACCG9876C1Z2",
      cin: "U72200KA2018PTC098765",
      din: ["09876543", "03456789", "05678901"],
      iec: "0798765432",
    },
    address: bangaloreAddress,
    billingAddress: bangaloreAddress,
    responsibleUserId: IDS.USERS.PARTNER_2,
    responsibleTeamId: IDS.TEAMS.TAXATION,
    services: [
      {
        ...baseEntity,
        id: "svc-global-itr",
        clientId: IDS.CLIENTS.GLOBAL_CORP,
        serviceType: "itr",
        serviceName: "ITR Filing",
        frequency: "annual",
        startDate: "2024-04-01",
        assignedUserId: IDS.USERS.SENIOR_2,
        assignedTeamId: IDS.TEAMS.TAXATION,
        billingMethod: "fixed_fee",
        rate: 75000,
        currency: "INR",
        isActive: true,
      },
      {
        ...baseEntity,
        id: "svc-global-gst",
        clientId: IDS.CLIENTS.GLOBAL_CORP,
        serviceType: "gst_monthly",
        serviceName: "GST Monthly Filing",
        frequency: "monthly",
        startDate: "2024-04-01",
        assignedUserId: IDS.USERS.SENIOR_2,
        assignedTeamId: IDS.TEAMS.GST,
        billingMethod: "fixed_fee",
        rate: 25000,
        currency: "INR",
        isActive: true,
      },
      {
        ...baseEntity,
        id: "svc-global-tds",
        clientId: IDS.CLIENTS.GLOBAL_CORP,
        serviceType: "tds_26q",
        serviceName: "TDS Non-Salary (26Q)",
        frequency: "quarterly",
        startDate: "2024-04-01",
        assignedUserId: IDS.USERS.ASSOCIATE_2,
        assignedTeamId: IDS.TEAMS.TAXATION,
        billingMethod: "fixed_fee",
        rate: 12000,
        currency: "INR",
        isActive: true,
      },
    ],
    complianceProfile: {
      applicableComplianceTypes: ["itr", "gst_monthly", "tds_26q"],
      financialYearStart: fyStart,
      gstFilingFrequency: "monthly",
      tdsApplicable: true,
      mcaApplicable: true,
      auditApplicable: true,
    },
    onboardingStatus: createOnboardingStatus("completed", 100),
    financialProfile: {
      annualTurnover: 500000000,
      taxableIncome: 80000000,
      gstLiability: 4500000,
      tdsLiability: 2500000,
      outstandingReceivables: 5000000,
      outstandingPayables: 3000000,
      creditLimit: 20000000,
      paymentTerms: 60,
      preferredPaymentMethod: "bank_transfer",
    },
    tags: ["it-services", "export", "large-corporate"],
    notes: "Large IT services company with export income. Multi-location operations.",
    portalAccessEnabled: true,
    portalInvitationSentAt: "2023-12-01T10:00:00Z",
  },
  {
    ...baseEntity,
    id: IDS.CLIENTS.TECH_STARTUP,
    name: "TechNova Solutions Pvt Ltd",
    legalName: "TechNova Solutions Private Limited",
    displayName: "TechNova Solutions",
    type: "private_limited",
    category: "advisory",
    status: "active",
    primaryContactId: IDS.CONTACTS.TECH_ARJUN,
    contacts: [],
    identifiers: {
      pan: "AACTN1111D",
      tan: "BLRN11111D",
      gstin: "29AACTN1111D1Z1",
      cin: "U72900KA2022PTC111111",
      din: ["01111111", "02222222"],
    },
    address: bangaloreAddress,
    billingAddress: bangaloreAddress,
    responsibleUserId: IDS.USERS.MANAGER_1,
    responsibleTeamId: IDS.TEAMS.ADVISORY,
    services: [
      {
        ...baseEntity,
        id: "svc-tech-itr",
        clientId: IDS.CLIENTS.TECH_STARTUP,
        serviceType: "itr",
        serviceName: "ITR Filing",
        frequency: "annual",
        startDate: "2024-04-01",
        assignedUserId: IDS.USERS.SENIOR_2,
        assignedTeamId: IDS.TEAMS.TAXATION,
        billingMethod: "fixed_fee",
        rate: 30000,
        currency: "INR",
        isActive: true,
      },
      {
        ...baseEntity,
        id: "svc-tech-gst",
        clientId: IDS.CLIENTS.TECH_STARTUP,
        serviceType: "gst_monthly",
        serviceName: "GST Monthly Filing",
        frequency: "monthly",
        startDate: "2024-04-01",
        assignedUserId: IDS.USERS.ASSOCIATE_2,
        assignedTeamId: IDS.TEAMS.GST,
        billingMethod: "fixed_fee",
        rate: 12000,
        currency: "INR",
        isActive: true,
      },
      {
        ...baseEntity,
        id: "svc-tech-advisory",
        clientId: IDS.CLIENTS.TECH_STARTUP,
        serviceType: "advisory_tax",
        serviceName: "Tax Advisory",
        description: "International tax and transfer pricing advisory",
        frequency: "continuous",
        startDate: "2024-04-01",
        assignedUserId: IDS.USERS.MANAGER_1,
        assignedTeamId: IDS.TEAMS.ADVISORY,
        billingMethod: "hourly",
        rate: 5000,
        currency: "INR",
        isActive: true,
      },
    ],
    complianceProfile: {
      applicableComplianceTypes: ["itr", "gst_monthly"],
      financialYearStart: fyStart,
      gstFilingFrequency: "monthly",
      tdsApplicable: true,
      mcaApplicable: true,
      auditApplicable: true,
    },
    onboardingStatus: createOnboardingStatus("completed", 100),
    financialProfile: {
      annualTurnover: 120000000,
      taxableIncome: 15000000,
      gstLiability: 1800000,
      outstandingReceivables: 1500000,
      outstandingPayables: 800000,
      paymentTerms: 30,
      preferredPaymentMethod: "bank_transfer",
    },
    tags: ["startup", "saas", "export", "transfer-pricing"],
    notes: "Fast-growing SaaS startup. Requires transfer pricing documentation.",
    portalAccessEnabled: true,
    portalInvitationSentAt: "2024-03-01T10:00:00Z",
  },
  {
    ...baseEntity,
    id: IDS.CLIENTS.RETAIL_CHAIN,
    name: "RetailMax Chain Pvt Ltd",
    legalName: "RetailMax Chain Private Limited",
    displayName: "RetailMax Chain",
    type: "private_limited",
    category: "compliance",
    status: "active",
    primaryContactId: IDS.CONTACTS.RETAIL_MEERA,
    contacts: [],
    identifiers: {
      pan: "AACRR2222E",
      tan: "MUMR22222E",
      gstin: "27AACRR2222E1Z0",
      cin: "U52100MH2019PTC222222",
      din: ["03333333", "04444444"],
    },
    address: mumbaiAddress,
    billingAddress: mumbaiAddress,
    responsibleUserId: IDS.USERS.PARTNER_1,
    responsibleTeamId: IDS.TEAMS.GST,
    services: [
      {
        ...baseEntity,
        id: "svc-retail-itr",
        clientId: IDS.CLIENTS.RETAIL_CHAIN,
        serviceType: "itr",
        serviceName: "ITR Filing",
        frequency: "annual",
        startDate: "2024-04-01",
        assignedUserId: IDS.USERS.SENIOR_1,
        assignedTeamId: IDS.TEAMS.TAXATION,
        billingMethod: "fixed_fee",
        rate: 60000,
        currency: "INR",
        isActive: true,
      },
      {
        ...baseEntity,
        id: "svc-retail-gst",
        clientId: IDS.CLIENTS.RETAIL_CHAIN,
        serviceType: "gst_monthly",
        serviceName: "GST Monthly Filing (Multi-state)",
        frequency: "monthly",
        startDate: "2024-04-01",
        assignedUserId: IDS.USERS.SENIOR_1,
        assignedTeamId: IDS.TEAMS.GST,
        billingMethod: "fixed_fee",
        rate: 30000,
        currency: "INR",
        isActive: true,
      },
    ],
    complianceProfile: {
      applicableComplianceTypes: ["itr", "gst_monthly"],
      financialYearStart: fyStart,
      gstFilingFrequency: "monthly",
      tdsApplicable: true,
      mcaApplicable: true,
      auditApplicable: true,
    },
    onboardingStatus: createOnboardingStatus("completed", 100),
    financialProfile: {
      annualTurnover: 800000000,
      taxableIncome: 120000000,
      gstLiability: 12000000,
      tdsLiability: 3000000,
      outstandingReceivables: 8000000,
      outstandingPayables: 5000000,
      creditLimit: 50000000,
      paymentTerms: 45,
      preferredPaymentMethod: "bank_transfer",
    },
    tags: ["retail", "multi-state-gst", "high-volume"],
    notes: "Large retail chain with pan-India presence. Multi-state GST registrations.",
    portalAccessEnabled: true,
    portalInvitationSentAt: "2024-01-20T10:00:00Z",
  },
  {
    ...baseEntity,
    id: IDS.CLIENTS.MANUFACTURING_CO,
    name: "Precision Manufacturing Co Pvt Ltd",
    legalName: "Precision Manufacturing Company Private Limited",
    displayName: "Precision Mfg Co",
    type: "private_limited",
    category: "multi_service",
    status: "active",
    primaryContactId: IDS.CONTACTS.MFG_VIKRAM,
    contacts: [],
    identifiers: {
      pan: "AACPM3333F",
      tan: "CHNM33333F",
      gstin: "33AACPM3333F1Z9",
      cin: "U29100TN2015PTC333333",
      din: ["05555555", "06666666"],
      iec: "0433333333",
    },
    address: {
      line1: "100 Industrial Estate",
      line2: "Ambattur",
      city: "Chennai",
      state: "Tamil Nadu",
      postalCode: "600058",
      country: "India",
    },
    billingAddress: {
      line1: "100 Industrial Estate",
      line2: "Ambattur",
      city: "Chennai",
      state: "Tamil Nadu",
      postalCode: "600058",
      country: "India",
    },
    responsibleUserId: IDS.USERS.PARTNER_2,
    responsibleTeamId: IDS.TEAMS.TAXATION,
    services: [
      {
        ...baseEntity,
        id: "svc-mfg-itr",
        clientId: IDS.CLIENTS.MANUFACTURING_CO,
        serviceType: "itr",
        serviceName: "ITR Filing",
        frequency: "annual",
        startDate: "2024-04-01",
        assignedUserId: IDS.USERS.SENIOR_2,
        assignedTeamId: IDS.TEAMS.TAXATION,
        billingMethod: "fixed_fee",
        rate: 55000,
        currency: "INR",
        isActive: true,
      },
      {
        ...baseEntity,
        id: "svc-mfg-gst",
        clientId: IDS.CLIENTS.MANUFACTURING_CO,
        serviceType: "gst_monthly",
        serviceName: "GST Monthly Filing",
        frequency: "monthly",
        startDate: "2024-04-01",
        assignedUserId: IDS.USERS.ASSOCIATE_2,
        assignedTeamId: IDS.TEAMS.GST,
        billingMethod: "fixed_fee",
        rate: 20000,
        currency: "INR",
        isActive: true,
      },
      {
        ...baseEntity,
        id: "svc-mfg-audit",
        clientId: IDS.CLIENTS.MANUFACTURING_CO,
        serviceType: "audit_statutory",
        serviceName: "Statutory Audit",
        frequency: "annual",
        startDate: "2024-04-01",
        assignedUserId: IDS.USERS.MANAGER_2,
        assignedTeamId: IDS.TEAMS.AUDIT,
        billingMethod: "fixed_fee",
        rate: 180000,
        currency: "INR",
        isActive: true,
      },
    ],
    complianceProfile: {
      applicableComplianceTypes: ["itr", "gst_monthly", "audit_statutory"],
      financialYearStart: fyStart,
      gstFilingFrequency: "monthly",
      tdsApplicable: true,
      mcaApplicable: true,
      auditApplicable: true,
    },
    onboardingStatus: createOnboardingStatus("completed", 100),
    financialProfile: {
      annualTurnover: 350000000,
      taxableIncome: 45000000,
      gstLiability: 4200000,
      tdsLiability: 1500000,
      outstandingReceivables: 3000000,
      outstandingPayables: 2000000,
      paymentTerms: 60,
      preferredPaymentMethod: "bank_transfer",
    },
    tags: ["manufacturing", "export", "audit-required"],
    notes: "Precision engineering manufacturer. Export-oriented unit.",
    portalAccessEnabled: true,
    portalInvitationSentAt: "2023-11-15T10:00:00Z",
  },
  {
    ...baseEntity,
    id: IDS.CLIENTS.HEALTHCARE_PVT,
    name: "MediCare Hospitals Pvt Ltd",
    legalName: "MediCare Hospitals Private Limited",
    displayName: "MediCare Hospitals",
    type: "private_limited",
    category: "audit",
    status: "active",
    primaryContactId: IDS.CONTACTS.HEALTH_DR,
    contacts: [],
    identifiers: {
      pan: "AACMH4444G",
      tan: "HYDM44444G",
      gstin: "36AACMH4444G1Z8",
      cin: "U85100TG2017PTC444444",
      din: ["07777777"],
    },
    address: {
      line1: "200 Medical District",
      line2: "Gachibowli",
      city: "Hyderabad",
      state: "Telangana",
      postalCode: "500032",
      country: "India",
    },
    billingAddress: {
      line1: "200 Medical District",
      line2: "Gachibowli",
      city: "Hyderabad",
      state: "Telangana",
      postalCode: "500032",
      country: "India",
    },
    responsibleUserId: IDS.USERS.PARTNER_2,
    responsibleTeamId: IDS.TEAMS.AUDIT,
    services: [
      {
        ...baseEntity,
        id: "svc-health-itr",
        clientId: IDS.CLIENTS.HEALTHCARE_PVT,
        serviceType: "itr",
        serviceName: "ITR Filing",
        frequency: "annual",
        startDate: "2024-04-01",
        assignedUserId: IDS.USERS.SENIOR_2,
        assignedTeamId: IDS.TEAMS.TAXATION,
        billingMethod: "fixed_fee",
        rate: 45000,
        currency: "INR",
        isActive: true,
      },
      {
        ...baseEntity,
        id: "svc-health-audit",
        clientId: IDS.CLIENTS.HEALTHCARE_PVT,
        serviceType: "audit_statutory",
        serviceName: "Statutory Audit",
        frequency: "annual",
        startDate: "2024-04-01",
        assignedUserId: IDS.USERS.MANAGER_2,
        assignedTeamId: IDS.TEAMS.AUDIT,
        billingMethod: "fixed_fee",
        rate: 150000,
        currency: "INR",
        isActive: true,
      },
    ],
    complianceProfile: {
      applicableComplianceTypes: ["itr", "audit_statutory"],
      financialYearStart: fyStart,
      tdsApplicable: true,
      mcaApplicable: true,
      auditApplicable: true,
    },
    onboardingStatus: createOnboardingStatus("completed", 100),
    financialProfile: {
      annualTurnover: 200000000,
      taxableIncome: 30000000,
      gstLiability: 0,
      tdsLiability: 1000000,
      outstandingReceivables: 2500000,
      outstandingPayables: 1500000,
      paymentTerms: 30,
      preferredPaymentMethod: "bank_transfer",
    },
    tags: ["healthcare", "hospital", "audit-required", "gst-exempt"],
    notes: "Hospital chain. GST exempt services. Audit mandatory.",
    portalAccessEnabled: true,
    portalInvitationSentAt: "2024-02-15T10:00:00Z",
  },
  {
    ...baseEntity,
    id: IDS.CLIENTS.FINTECH_LLP,
    name: "FinServe Advisory LLP",
    legalName: "FinServe Advisory Limited Liability Partnership",
    displayName: "FinServe Advisory",
    type: "llp",
    category: "advisory",
    status: "active",
    primaryContactId: IDS.CONTACTS.FINTECH_NEHA,
    contacts: [],
    identifiers: {
      pan: "AABFF5555H",
      tan: "MUMF55555H",
      gstin: "27AABFF5555H1Z7",
      cin: "AAB-5555",
    },
    address: mumbaiAddress,
    billingAddress: mumbaiAddress,
    responsibleUserId: IDS.USERS.MANAGER_1,
    responsibleTeamId: IDS.TEAMS.ADVISORY,
    services: [
      {
        ...baseEntity,
        id: "svc-fintech-itr",
        clientId: IDS.CLIENTS.FINTECH_LLP,
        serviceType: "itr",
        serviceName: "ITR Filing for LLP",
        frequency: "annual",
        startDate: "2024-04-01",
        assignedUserId: IDS.USERS.SENIOR_2,
        assignedTeamId: IDS.TEAMS.TAXATION,
        billingMethod: "fixed_fee",
        rate: 40000,
        currency: "INR",
        isActive: true,
      },
      {
        ...baseEntity,
        id: "svc-fintech-advisory",
        clientId: IDS.CLIENTS.FINTECH_LLP,
        serviceType: "advisory_corporate",
        serviceName: "Corporate Advisory",
        description: "Fundraising, valuation, and M&A advisory",
        frequency: "continuous",
        startDate: "2024-04-01",
        assignedUserId: IDS.USERS.MANAGER_1,
        assignedTeamId: IDS.TEAMS.ADVISORY,
        billingMethod: "hourly",
        rate: 8000,
        currency: "INR",
        isActive: true,
      },
    ],
    complianceProfile: {
      applicableComplianceTypes: ["itr"],
      financialYearStart: fyStart,
      tdsApplicable: true,
      mcaApplicable: false,
      auditApplicable: false,
    },
    onboardingStatus: createOnboardingStatus("completed", 100),
    financialProfile: {
      annualTurnover: 60000000,
      taxableIncome: 18000000,
      gstLiability: 540000,
      outstandingReceivables: 800000,
      outstandingPayables: 400000,
      paymentTerms: 30,
      preferredPaymentMethod: "bank_transfer",
    },
    tags: ["fintech", "advisory", "fundraising"],
    notes: "Financial advisory firm. High-value advisory engagements.",
    portalAccessEnabled: true,
    portalInvitationSentAt: "2024-03-15T10:00:00Z",
  },
  {
    ...baseEntity,
    id: IDS.CLIENTS.REAL_ESTATE,
    name: "UrbanSpace Developers Pvt Ltd",
    legalName: "UrbanSpace Developers Private Limited",
    displayName: "UrbanSpace Developers",
    type: "private_limited",
    category: "compliance",
    status: "active",
    primaryContactId: IDS.CONTACTS.REAL_RAHUL,
    contacts: [],
    identifiers: {
      pan: "AACUD6666I",
      tan: "BLRD66666I",
      gstin: "29AACUD6666I1Z6",
      cin: "U45200KA2020PTC666666",
      din: ["08888888", "09999999"],
    },
    address: bangaloreAddress,
    billingAddress: bangaloreAddress,
    responsibleUserId: IDS.USERS.PARTNER_1,
    responsibleTeamId: IDS.TEAMS.TAXATION,
    services: [
      {
        ...baseEntity,
        id: "svc-real-itr",
        clientId: IDS.CLIENTS.REAL_ESTATE,
        serviceType: "itr",
        serviceName: "ITR Filing",
        frequency: "annual",
        startDate: "2024-04-01",
        assignedUserId: IDS.USERS.SENIOR_1,
        assignedTeamId: IDS.TEAMS.TAXATION,
        billingMethod: "fixed_fee",
        rate: 50000,
        currency: "INR",
        isActive: true,
      },
      {
        ...baseEntity,
        id: "svc-real-gst",
        clientId: IDS.CLIENTS.REAL_ESTATE,
        serviceType: "gst_monthly",
        serviceName: "GST Monthly Filing",
        frequency: "monthly",
        startDate: "2024-04-01",
        assignedUserId: IDS.USERS.SENIOR_1,
        assignedTeamId: IDS.TEAMS.GST,
        billingMethod: "fixed_fee",
        rate: 18000,
        currency: "INR",
        isActive: true,
      },
    ],
    complianceProfile: {
      applicableComplianceTypes: ["itr", "gst_monthly"],
      financialYearStart: fyStart,
      gstFilingFrequency: "monthly",
      tdsApplicable: true,
      mcaApplicable: true,
      auditApplicable: true,
    },
    onboardingStatus: createOnboardingStatus("completed", 100),
    financialProfile: {
      annualTurnover: 400000000,
      taxableIncome: 60000000,
      gstLiability: 4800000,
      tdsLiability: 2000000,
      outstandingReceivables: 4000000,
      outstandingPayables: 3000000,
      paymentTerms: 60,
      preferredPaymentMethod: "bank_transfer",
    },
    tags: ["real-estate", "construction", "gst-works-contract"],
    notes: "Real estate developer. Works contract GST implications.",
    portalAccessEnabled: true,
    portalInvitationSentAt: "2024-02-20T10:00:00Z",
  },
];

export const mockContacts: Contact[] = [
  {
    ...baseEntity,
    id: IDS.CONTACTS.ABC_RAJESH,
    clientId: IDS.CLIENTS.ABC_PVT_LTD,
    firstName: "Rajesh",
    lastName: "Kumar",
    email: "rajesh.kumar@abc.com",
    phone: "+91-9811122233",
    mobile: "+91-9811122233",
    designation: "CFO",
    department: "Finance",
    isPrimary: true,
    isAuthorizedSignatory: true,
    receivesCommunications: true,
    preferredChannel: "email",
  },
  {
    ...baseEntity,
    id: IDS.CONTACTS.ABC_PRIYA,
    clientId: IDS.CLIENTS.ABC_PVT_LTD,
    firstName: "Priya",
    lastName: "Sharma",
    email: "priya.sharma@abc.com",
    phone: "+91-9811122244",
    mobile: "+91-9811122244",
    designation: "Company Secretary",
    department: "Secretarial",
    isPrimary: false,
    isAuthorizedSignatory: true,
    receivesCommunications: true,
    preferredChannel: "email",
  },
  {
    ...baseEntity,
    id: IDS.CONTACTS.XYZ_AMIT,
    clientId: IDS.CLIENTS.XYZ_LLP,
    firstName: "Amit",
    lastName: "Desai",
    email: "amit.desai@xyz.com",
    phone: "+91-9822233344",
    mobile: "+91-9822233344",
    designation: "Designated Partner",
    department: "Management",
    isPrimary: true,
    isAuthorizedSignatory: true,
    receivesCommunications: true,
    preferredChannel: "whatsapp",
  },
  {
    ...baseEntity,
    id: IDS.CONTACTS.SHARMA_RAVI,
    clientId: IDS.CLIENTS.SHARMA_PROP,
    firstName: "Ravi",
    lastName: "Sharma",
    email: "ravi.sharma@sharmaassoc.com",
    phone: "+91-9833344455",
    mobile: "+91-9833344455",
    designation: "Proprietor",
    department: "Owner",
    isPrimary: true,
    isAuthorizedSignatory: true,
    receivesCommunications: true,
    preferredChannel: "call",
  },
  {
    ...baseEntity,
    id: IDS.CONTACTS.GLOBAL_SARAH,
    clientId: IDS.CLIENTS.GLOBAL_CORP,
    firstName: "Sarah",
    lastName: "Johnson",
    email: "sarah.johnson@globalcorp.com",
    phone: "+91-9844455566",
    mobile: "+91-9844455566",
    designation: "Finance Controller",
    department: "Finance",
    isPrimary: true,
    isAuthorizedSignatory: true,
    receivesCommunications: true,
    preferredChannel: "email",
  },
  {
    ...baseEntity,
    id: IDS.CONTACTS.TECH_ARJUN,
    clientId: IDS.CLIENTS.TECH_STARTUP,
    firstName: "Arjun",
    lastName: "Kapoor",
    email: "arjun.kapoor@technova.com",
    phone: "+91-9855566677",
    mobile: "+91-9855566677",
    designation: "Founder & CEO",
    department: "Management",
    isPrimary: true,
    isAuthorizedSignatory: true,
    receivesCommunications: true,
    preferredChannel: "whatsapp",
  },
  {
    ...baseEntity,
    id: IDS.CONTACTS.RETAIL_MEERA,
    clientId: IDS.CLIENTS.RETAIL_CHAIN,
    firstName: "Meera",
    lastName: "Nair",
    email: "meera.nair@retailmax.com",
    phone: "+91-9866677788",
    mobile: "+91-9866677788",
    designation: "Head of Finance",
    department: "Finance",
    isPrimary: true,
    isAuthorizedSignatory: true,
    receivesCommunications: true,
    preferredChannel: "email",
  },
  {
    ...baseEntity,
    id: IDS.CONTACTS.MFG_VIKRAM,
    clientId: IDS.CLIENTS.MANUFACTURING_CO,
    firstName: "Vikram",
    lastName: "Singh",
    email: "vikram.singh@precisionmfg.com",
    phone: "+91-9877788899",
    mobile: "+91-9877788899",
    designation: "Director - Finance",
    department: "Finance",
    isPrimary: true,
    isAuthorizedSignatory: true,
    receivesCommunications: true,
    preferredChannel: "email",
  },
  {
    ...baseEntity,
    id: IDS.CONTACTS.HEALTH_DR,
    clientId: IDS.CLIENTS.HEALTHCARE_PVT,
    firstName: "Dr. Anjali",
    lastName: "Reddy",
    email: "dr.anjali@medicare.com",
    phone: "+91-9888899900",
    mobile: "+91-9888899900",
    designation: "Medical Director",
    department: "Administration",
    isPrimary: true,
    isAuthorizedSignatory: true,
    receivesCommunications: true,
    preferredChannel: "email",
  },
  {
    ...baseEntity,
    id: IDS.CONTACTS.FINTECH_NEHA,
    clientId: IDS.CLIENTS.FINTECH_LLP,
    firstName: "Neha",
    lastName: "Mehta",
    email: "neha.mehta@finserve.com",
    phone: "+91-9899900011",
    mobile: "+91-9899900011",
    designation: "Managing Partner",
    department: "Management",
    isPrimary: true,
    isAuthorizedSignatory: true,
    receivesCommunications: true,
    preferredChannel: "whatsapp",
  },
  {
    ...baseEntity,
    id: IDS.CONTACTS.REAL_RAHUL,
    clientId: IDS.CLIENTS.REAL_ESTATE,
    firstName: "Rahul",
    lastName: "Agarwal",
    email: "rahul.agarwal@urbanspace.com",
    phone: "+91-9800011122",
    mobile: "+91-9800011122",
    designation: "CFO",
    department: "Finance",
    isPrimary: true,
    isAuthorizedSignatory: true,
    receivesCommunications: true,
    preferredChannel: "email",
  },
];

export const getClientById = (id: string): Client | undefined => mockClients.find((c) => c.id === id);
export const getClientsByUser = (userId: string): Client[] => mockClients.filter((c) => c.responsibleUserId === userId);
export const getClientsByTeam = (teamId: string): Client[] => mockClients.filter((c) => c.responsibleTeamId === teamId);
export const getClientsByStatus = (status: ClientStatus): Client[] => mockClients.filter((c) => c.status === status);
export const getContactsByClient = (clientId: string): Contact[] => mockContacts.filter((c) => c.clientId === clientId);
export const getContactById = (id: string): Contact | undefined => mockContacts.find((c) => c.id === id);
