import type { Document, DocumentCategory, DocumentType } from "@/types";

// biome-ignore lint/suspicious/noImportCycles: Mock data cross-references are intentional
import { mockCommunications } from "./communications";
import { IDS } from "./ids";

const now = new Date().toISOString();
const tenantId = IDS.TENANT;

const baseEntity = {
  tenantId,
  createdAt: now,
  updatedAt: now,
  createdBy: IDS.USERS.ADMIN,
  updatedBy: IDS.USERS.ADMIN,
};

export const mockDocuments: Document[] = [
  {
    ...baseEntity,
    id: IDS.DOCUMENTS.ABC_PAN,
    documentNumber: "DOC-ABC-PAN-001",
    fileName: "ABC_Pvt_Ltd_PAN_Card.pdf",
    originalFileName: "PAN_Card_ABC.pdf",
    fileSize: 245760,
    mimeType: "application/pdf",
    fileUrl: "/mock-documents/abc-pan.pdf",
    thumbnailUrl: "/mock-thumbnails/abc-pan-thumb.jpg",
    clientId: IDS.CLIENTS.ABC_PVT_LTD,
    matterId: IDS.MATTERS.ABC_ITR_FY24,
    uploadedById: IDS.USERS.SENIOR_1,
    category: "kyc",
    documentType: "pan_card",
    tags: ["kyc", "pan", "incorporation"],
    version: 1,
    isLatestVersion: true,
    ocrStatus: "completed",
    ocrText: "Permanent Account Number: AABCA1234A\nName: ABC PRIVATE LIMITED\nDate of Incorporation: 15/01/2020",
    classification: {
      documentType: "pan_card",
      confidence: 0.99,
      extractedFields: { pan: "AABCA1234A", companyName: "ABC PRIVATE LIMITED" },
      classifiedAt: now,
      classifiedBy: "ai",
    },
    metadata: { panNumber: "AABCA1234A", entityName: "ABC PRIVATE LIMITED" },
    isConfidential: true,
    retentionPolicy: { retentionYears: 10, disposalAction: "archive", legalBasis: "Income Tax Act" },
    virusScanStatus: "clean",
    virusScannedAt: now,
  },
  {
    ...baseEntity,
    id: IDS.DOCUMENTS.ABC_AADHAAR,
    documentNumber: "DOC-ABC-AADH-001",
    fileName: "ABC_Directors_Aadhaar.pdf",
    originalFileName: "Directors_Aadhaar.pdf",
    fileSize: 512000,
    mimeType: "application/pdf",
    fileUrl: "/mock-documents/abc-aadhaar.pdf",
    clientId: IDS.CLIENTS.ABC_PVT_LTD,
    matterId: IDS.MATTERS.ABC_ITR_FY24,
    uploadedById: IDS.USERS.SENIOR_1,
    category: "kyc",
    documentType: "aadhaar_card",
    tags: ["kyc", "aadhaar", "directors"],
    version: 1,
    isLatestVersion: true,
    ocrStatus: "completed",
    ocrText: "Aadhaar numbers for directors: 1234-5678-9012, 2345-6789-0123",
    classification: {
      documentType: "aadhaar_card",
      confidence: 0.95,
      extractedFields: { aadhaarNumbers: ["1234-5678-9012", "2345-6789-0123"] },
      classifiedAt: now,
      classifiedBy: "ai",
    },
    metadata: { directorCount: 2 },
    isConfidential: true,
    retentionPolicy: { retentionYears: 10, disposalAction: "archive" },
    virusScanStatus: "clean",
    virusScannedAt: now,
  },
  {
    ...baseEntity,
    id: IDS.DOCUMENTS.ABC_GST_REG,
    documentNumber: "DOC-ABC-GST-001",
    fileName: "ABC_GST_Registration_Certificate.pdf",
    originalFileName: "GST_REG_06AABCA1234A1Z5.pdf",
    fileSize: 189440,
    mimeType: "application/pdf",
    fileUrl: "/mock-documents/abc-gst-reg.pdf",
    clientId: IDS.CLIENTS.ABC_PVT_LTD,
    matterId: IDS.MATTERS.ABC_GST_Q1,
    uploadedById: IDS.USERS.SENIOR_1,
    category: "registration",
    documentType: "gst_registration",
    tags: ["gst", "registration", "certificate"],
    version: 1,
    isLatestVersion: true,
    ocrStatus: "completed",
    ocrText:
      "GSTIN: 06AABCA1234A1Z5\nLegal Name: ABC PRIVATE LIMITED\nTrade Name: ABC Pvt Ltd\nRegistration Date: 01/02/2020",
    classification: {
      documentType: "gst_registration",
      confidence: 0.98,
      extractedFields: { gstin: "06AABCA1234A1Z5", legalName: "ABC PRIVATE LIMITED" },
      classifiedAt: now,
      classifiedBy: "ai",
    },
    metadata: { gstin: "06AABCA1234A1Z5", registrationDate: "2020-02-01" },
    isConfidential: false,
    retentionPolicy: { retentionYears: 8, disposalAction: "archive" },
    virusScanStatus: "clean",
    virusScannedAt: now,
  },
  {
    ...baseEntity,
    id: IDS.DOCUMENTS.ABC_FINANCIALS,
    documentNumber: "DOC-ABC-FIN-001",
    fileName: "ABC_Audited_Financials_FY24.pdf",
    originalFileName: "Audited_Financial_Statements_FY2024.pdf",
    fileSize: 2048000,
    mimeType: "application/pdf",
    fileUrl: "/mock-documents/abc-financials.pdf",
    clientId: IDS.CLIENTS.ABC_PVT_LTD,
    matterId: IDS.MATTERS.ABC_ITR_FY24,
    uploadedById: IDS.CONTACTS.ABC_RAJESH,
    category: "financial_statement",
    documentType: "financial_statements",
    tags: ["financials", "audited", "fy24", "itr"],
    version: 1,
    isLatestVersion: true,
    ocrStatus: "completed",
    ocrText:
      "ABC PRIVATE LIMITED\nAudited Financial Statements for FY 2023-24\nTotal Revenue: Rs. 15,00,00,000\nProfit Before Tax: Rs. 3,50,00,000\nProfit After Tax: Rs. 2,50,00,000",
    classification: {
      documentType: "financial_statements",
      confidence: 0.92,
      extractedFields: { revenue: 150000000, pbt: 35000000, pat: 25000000, financialYear: "2023-24" },
      classifiedAt: now,
      classifiedBy: "ai",
    },
    metadata: { financialYear: "2023-24", audited: true, revenue: 150000000 },
    isConfidential: true,
    retentionPolicy: { retentionYears: 10, disposalAction: "archive", legalBasis: "Companies Act" },
    virusScanStatus: "clean",
    virusScannedAt: now,
  },
  {
    ...baseEntity,
    id: IDS.DOCUMENTS.ABC_FORM16,
    documentNumber: "DOC-ABC-F16-001",
    fileName: "ABC_Form16_FY24.pdf",
    originalFileName: "Form16_FY2024.pdf",
    fileSize: 345600,
    mimeType: "application/pdf",
    fileUrl: "/mock-documents/abc-form16.pdf",
    clientId: IDS.CLIENTS.ABC_PVT_LTD,
    matterId: IDS.MATTERS.ABC_ITR_FY24,
    uploadedById: IDS.USERS.ASSOCIATE_1,
    category: "tax_return",
    documentType: "form_16",
    tags: ["form16", "tds", "salary", "fy24"],
    version: 1,
    isLatestVersion: true,
    ocrStatus: "completed",
    ocrText:
      "FORM NO. 16\nCertificate under section 203 of the Income-tax Act, 1961\nTotal TDS deducted: Rs. 45,00,000",
    classification: {
      documentType: "form_16",
      confidence: 0.97,
      extractedFields: { tdsAmount: 4500000, financialYear: "2023-24" },
      classifiedAt: now,
      classifiedBy: "ai",
    },
    metadata: { tdsAmount: 4500000, financialYear: "2023-24" },
    isConfidential: true,
    retentionPolicy: { retentionYears: 10, disposalAction: "archive" },
    virusScanStatus: "clean",
    virusScannedAt: now,
  },
  {
    ...baseEntity,
    id: IDS.DOCUMENTS.ABC_26AS,
    documentNumber: "DOC-ABC-26AS-001",
    fileName: "ABC_Form26AS_FY24.pdf",
    originalFileName: "Form26AS_FY2024.pdf",
    fileSize: 287600,
    mimeType: "application/pdf",
    fileUrl: "/mock-documents/abc-26as.pdf",
    clientId: IDS.CLIENTS.ABC_PVT_LTD,
    matterId: IDS.MATTERS.ABC_ITR_FY24,
    uploadedById: IDS.USERS.SENIOR_1,
    category: "tax_return",
    documentType: "form_26as",
    tags: ["form26as", "tds", "tax-credit", "fy24"],
    version: 1,
    isLatestVersion: true,
    ocrStatus: "completed",
    ocrText: "FORM 26AS - Annual Tax Statement\nPAN: AABCA1234A\nTotal Tax Credits: Rs. 48,00,000",
    classification: {
      documentType: "form_26as",
      confidence: 0.96,
      extractedFields: { totalTaxCredits: 4800000, financialYear: "2023-24" },
      classifiedAt: now,
      classifiedBy: "ai",
    },
    metadata: { totalTaxCredits: 4800000, financialYear: "2023-24" },
    isConfidential: true,
    retentionPolicy: { retentionYears: 10, disposalAction: "archive" },
    virusScanStatus: "clean",
    virusScannedAt: now,
  },
  {
    ...baseEntity,
    id: IDS.DOCUMENTS.XYZ_PAN,
    documentNumber: "DOC-XYZ-PAN-001",
    fileName: "XYZ_LLP_PAN_Card.pdf",
    originalFileName: "PAN_XYZ_LLP.pdf",
    fileSize: 198400,
    mimeType: "application/pdf",
    fileUrl: "/mock-documents/xyz-pan.pdf",
    clientId: IDS.CLIENTS.XYZ_LLP,
    matterId: IDS.MATTERS.XYZ_ITR_FY24,
    uploadedById: IDS.USERS.ASSOCIATE_1,
    category: "kyc",
    documentType: "pan_card",
    tags: ["kyc", "pan", "llp"],
    version: 1,
    isLatestVersion: true,
    ocrStatus: "completed",
    classification: {
      documentType: "pan_card",
      confidence: 0.99,
      extractedFields: { pan: "AABFX5678B" },
      classifiedAt: now,
      classifiedBy: "ai",
    },
    metadata: { panNumber: "AABFX5678B", entityType: "LLP" },
    isConfidential: true,
    retentionPolicy: { retentionYears: 10, disposalAction: "archive" },
    virusScanStatus: "clean",
    virusScannedAt: now,
  },
  {
    ...baseEntity,
    id: IDS.DOCUMENTS.XYZ_GST_REG,
    documentNumber: "DOC-XYZ-GST-001",
    fileName: "XYZ_GST_Registration.pdf",
    originalFileName: "GST_REG_27AABFX5678B1Z4.pdf",
    fileSize: 176000,
    mimeType: "application/pdf",
    fileUrl: "/mock-documents/xyz-gst-reg.pdf",
    clientId: IDS.CLIENTS.XYZ_LLP,
    matterId: IDS.MATTERS.XYZ_GST_MONTHLY,
    uploadedById: IDS.USERS.ASSOCIATE_1,
    category: "registration",
    documentType: "gst_registration",
    tags: ["gst", "registration", "qrmp"],
    version: 1,
    isLatestVersion: true,
    ocrStatus: "completed",
    classification: {
      documentType: "gst_registration",
      confidence: 0.98,
      extractedFields: { gstin: "27AABFX5678B1Z4" },
      classifiedAt: now,
      classifiedBy: "ai",
    },
    metadata: { gstin: "27AABFX5678B1Z4", scheme: "QRMP" },
    isConfidential: false,
    retentionPolicy: { retentionYears: 8, disposalAction: "archive" },
    virusScanStatus: "clean",
    virusScannedAt: now,
  },
  {
    ...baseEntity,
    id: IDS.DOCUMENTS.SHARMA_PAN,
    documentNumber: "DOC-SHA-PAN-001",
    fileName: "Sharma_Proprietor_PAN.pdf",
    originalFileName: "PAN_BFPPS1234K.pdf",
    fileSize: 156000,
    mimeType: "application/pdf",
    fileUrl: "/mock-documents/sharma-pan.pdf",
    clientId: IDS.CLIENTS.SHARMA_PROP,
    matterId: IDS.MATTERS.SHARMA_ITR_FY24,
    uploadedById: IDS.CONTACTS.SHARMA_RAVI,
    category: "kyc",
    documentType: "pan_card",
    tags: ["kyc", "pan", "proprietorship"],
    version: 1,
    isLatestVersion: true,
    ocrStatus: "completed",
    classification: {
      documentType: "pan_card",
      confidence: 0.99,
      extractedFields: { pan: "BFPPS1234K" },
      classifiedAt: now,
      classifiedBy: "ai",
    },
    metadata: { panNumber: "BFPPS1234K", holderType: "Individual" },
    isConfidential: true,
    retentionPolicy: { retentionYears: 10, disposalAction: "archive" },
    virusScanStatus: "clean",
    virusScannedAt: now,
  },
  {
    ...baseEntity,
    id: IDS.DOCUMENTS.GLOBAL_INCORP,
    documentNumber: "DOC-GLB-INC-001",
    fileName: "Global_Corp_Certificate_of_Incorporation.pdf",
    originalFileName: "COI_U72200KA2018PTC098765.pdf",
    fileSize: 432000,
    mimeType: "application/pdf",
    fileUrl: "/mock-documents/global-incorp.pdf",
    clientId: IDS.CLIENTS.GLOBAL_CORP,
    matterId: IDS.MATTERS.GLOBAL_ITR_FY24,
    uploadedById: IDS.USERS.SENIOR_2,
    category: "registration",
    documentType: "incorporation_certificate",
    tags: ["incorporation", "certificate", "cin"],
    version: 1,
    isLatestVersion: true,
    ocrStatus: "completed",
    classification: {
      documentType: "incorporation_certificate",
      confidence: 0.98,
      extractedFields: { cin: "U72200KA2018PTC098765" },
      classifiedAt: now,
      classifiedBy: "ai",
    },
    metadata: { cin: "U72200KA2018PTC098765", incorporationDate: "2018-06-15" },
    isConfidential: false,
    retentionPolicy: { retentionYears: 15, disposalAction: "archive", legalBasis: "Companies Act" },
    virusScanStatus: "clean",
    virusScannedAt: now,
  },
];

export const getDocumentsByClient = (clientId: string): Document[] =>
  mockDocuments.filter((d) => d.clientId === clientId);

export const getDocumentsByMatter = (matterId: string): Document[] =>
  mockDocuments.filter((d) => d.matterId === matterId);

export const getDocumentsByTask = (taskId: string): Document[] => mockDocuments.filter((d) => d.taskId === taskId);

export const getDocumentsByCategory = (category: DocumentCategory): Document[] =>
  mockDocuments.filter((d) => d.category === category);

export const getDocumentsByType = (documentType: DocumentType): Document[] =>
  mockDocuments.filter((d) => d.documentType === documentType);

export const getDocumentById = (id: string): Document | undefined => mockDocuments.find((d) => d.id === id);

export const getDocumentsByUploadedBy = (userId: string): Document[] =>
  mockDocuments.filter((d) => d.uploadedById === userId);

export const getDocumentsByComplianceCycle = (complianceCycleId: string): Document[] =>
  mockDocuments.filter((d) => d.complianceCycleId === complianceCycleId);

export const getLatestDocuments = (limit = 10): Document[] =>
  [...mockDocuments].sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()).slice(0, limit);

export const getDocumentsByConversation = (conversationId: string): Document[] => {
  const commIds = mockCommunications.filter((c) => c.conversationId === conversationId).map((c) => c.id);
  return mockDocuments.filter((d) => d.sourceCommunicationId && commIds.includes(d.sourceCommunicationId));
};
