import type {
  ChecklistItem,
  Matter,
  MatterStage,
  MatterStageHistory,
  MatterStatus,
  Period,
  Subtask,
  Task,
  TaskStatus,
} from "@/types";

// biome-ignore lint/suspicious/noImportCycles: Mock data cross-references are intentional
import { mockCommunications } from "./communications";
import { IDS } from "./ids";

const now = new Date().toISOString();
const tenantId = IDS.TENANT;

const baseEntity = {
  tenantId,
  createdAt: now,
  updatedAt: now,
  createdBy: IDS.USERS.ADMIN,
  updatedBy: IDS.USERS.ADMIN,
};

const fy24Period: Period = {
  label: "FY 2024-25",
  startDate: "2024-04-01",
  endDate: "2025-03-31",
  financialYear: "2024-25",
  assessmentYear: "2025-26",
};

const q1Period: Period = {
  label: "Q1 2024-25 (Apr-Jun)",
  startDate: "2024-04-01",
  endDate: "2024-06-30",
  financialYear: "2024-25",
};

const aprPeriod: Period = {
  label: "April 2024",
  startDate: "2024-04-01",
  endDate: "2024-04-30",
  financialYear: "2024-25",
};

const _mayPeriod: Period = {
  label: "May 2024",
  startDate: "2024-05-01",
  endDate: "2024-05-31",
  financialYear: "2024-25",
};

const createStageHistory = (
  stages: { stage: MatterStage; date: string; by: string; notes?: string }[],
): MatterStageHistory[] =>
  stages.map((s) => ({
    stage: s.stage,
    changedAt: s.date,
    changedBy: s.by as any,
    notes: s.notes,
  }));

export const mockMatters: Matter[] = [
  {
    ...baseEntity,
    id: IDS.MATTERS.ABC_ITR_FY24,
    matterNumber: "MTR-ABC-ITR-24-001",
    name: "ABC Pvt Ltd - ITR FY 2024-25",
    description: "Annual Income Tax Return filing for ABC Private Limited for FY 2024-25 (AY 2025-26)",
    clientId: IDS.CLIENTS.ABC_PVT_LTD,
    serviceType: "itr",
    serviceName: "Income Tax Return Filing",
    period: fy24Period,
    status: "in_progress",
    priority: "high",
    assignedUserId: IDS.USERS.SENIOR_1,
    assignedTeamId: IDS.TEAMS.TAXATION,
    supervisingPartnerId: IDS.USERS.PARTNER_1,
    dueDate: "2024-10-31",
    estimatedHours: 40,
    actualHours: 22,
    progress: 55,
    stage: "in_progress",
    stageHistory: createStageHistory([
      { stage: "created", date: "2024-04-15T10:00:00Z", by: IDS.USERS.ADMIN },
      {
        stage: "information_pending",
        date: "2024-04-20T10:00:00Z",
        by: IDS.USERS.SENIOR_1,
        notes: "Waiting for financial statements",
      },
      {
        stage: "documents_pending",
        date: "2024-05-01T10:00:00Z",
        by: IDS.USERS.SENIOR_1,
        notes: "Form 26AS and Form 16 received",
      },
      { stage: "in_progress", date: "2024-05-15T10:00:00Z", by: IDS.USERS.SENIOR_1, notes: "Started computation" },
    ]),
    billingMethod: "fixed_fee",
    budgetAmount: 50000,
    billedAmount: 0,
    tags: ["itr", "fy24", "priority"],
    isBillable: true,
    complianceCycleId: IDS.COMPLIANCE_CYCLES.ABC_ITR_FY24,
  },
  {
    ...baseEntity,
    id: IDS.MATTERS.ABC_GST_Q1,
    matterNumber: "MTR-ABC-GST-24-001",
    name: "ABC Pvt Ltd - GST Q1 2024-25",
    description: "GST Returns (GSTR-1 & GSTR-3B) for April-June 2024 quarter",
    clientId: IDS.CLIENTS.ABC_PVT_LTD,
    serviceType: "gst_monthly",
    serviceName: "GST Monthly Return Filing",
    period: q1Period,
    status: "ready_for_review",
    priority: "high",
    assignedUserId: IDS.USERS.SENIOR_1,
    assignedTeamId: IDS.TEAMS.GST,
    supervisingPartnerId: IDS.USERS.PARTNER_1,
    dueDate: "2024-07-11",
    estimatedHours: 12,
    actualHours: 10,
    progress: 90,
    stage: "ready_for_review",
    stageHistory: createStageHistory([
      { stage: "created", date: "2024-04-01T10:00:00Z", by: IDS.USERS.ADMIN },
      { stage: "documents_pending", date: "2024-04-05T10:00:00Z", by: IDS.USERS.SENIOR_1 },
      { stage: "in_progress", date: "2024-06-15T10:00:00Z", by: IDS.USERS.SENIOR_1 },
      {
        stage: "ready_for_review",
        date: "2024-07-05T10:00:00Z",
        by: IDS.USERS.SENIOR_1,
        notes: "Ready for partner review",
      },
    ]),
    billingMethod: "fixed_fee",
    budgetAmount: 45000,
    billedAmount: 0,
    tags: ["gst", "q1", "review-pending"],
    isBillable: true,
    complianceCycleId: IDS.COMPLIANCE_CYCLES.ABC_GST_APR,
  },
  {
    ...baseEntity,
    id: IDS.MATTERS.ABC_TDS_Q1,
    matterNumber: "MTR-ABC-TDS-24-001",
    name: "ABC Pvt Ltd - TDS Q1 2024-25 (24Q)",
    description: "Quarterly TDS Return Form 24Q for salary payments",
    clientId: IDS.CLIENTS.ABC_PVT_LTD,
    serviceType: "tds_24q",
    serviceName: "TDS Return Filing (24Q)",
    period: q1Period,
    status: "documents_pending",
    priority: "medium",
    assignedUserId: IDS.USERS.ASSOCIATE_1,
    assignedTeamId: IDS.TEAMS.TAXATION,
    supervisingPartnerId: IDS.USERS.PARTNER_1,
    dueDate: "2024-07-31",
    estimatedHours: 8,
    actualHours: 2,
    progress: 25,
    stage: "documents_pending",
    stageHistory: createStageHistory([
      { stage: "created", date: "2024-04-01T10:00:00Z", by: IDS.USERS.ADMIN },
      {
        stage: "documents_pending",
        date: "2024-04-10T10:00:00Z",
        by: IDS.USERS.ASSOCIATE_1,
        notes: "Waiting for challan details",
      },
    ]),
    billingMethod: "fixed_fee",
    budgetAmount: 8000,
    billedAmount: 0,
    tags: ["tds", "24q", "q1"],
    isBillable: true,
    complianceCycleId: IDS.COMPLIANCE_CYCLES.ABC_TDS_Q1,
  },
  {
    ...baseEntity,
    id: IDS.MATTERS.ABC_AUDIT_FY24,
    matterNumber: "MTR-ABC-AUD-24-001",
    name: "ABC Pvt Ltd - Statutory Audit FY 2024-25",
    description: "Annual statutory audit under Companies Act 2013",
    clientId: IDS.CLIENTS.ABC_PVT_LTD,
    serviceType: "audit_statutory",
    serviceName: "Statutory Audit",
    period: fy24Period,
    status: "planning",
    priority: "high",
    assignedUserId: IDS.USERS.MANAGER_2,
    assignedTeamId: IDS.TEAMS.AUDIT,
    supervisingPartnerId: IDS.USERS.PARTNER_2,
    dueDate: "2024-09-30",
    estimatedHours: 200,
    actualHours: 15,
    progress: 8,
    stage: "information_pending",
    stageHistory: createStageHistory([
      { stage: "created", date: "2024-04-01T10:00:00Z", by: IDS.USERS.ADMIN },
      {
        stage: "information_pending",
        date: "2024-04-10T10:00:00Z",
        by: IDS.USERS.MANAGER_2,
        notes: "Planning phase - awaiting trial balance",
      },
    ]),
    billingMethod: "fixed_fee",
    budgetAmount: 200000,
    billedAmount: 0,
    tags: ["audit", "statutory", "fy24", "planning"],
    isBillable: true,
  },
  {
    ...baseEntity,
    id: IDS.MATTERS.XYZ_ITR_FY24,
    matterNumber: "MTR-XYZ-ITR-24-001",
    name: "XYZ LLP - ITR FY 2024-25",
    description: "Annual ITR-5 filing for XYZ LLP",
    clientId: IDS.CLIENTS.XYZ_LLP,
    serviceType: "itr",
    serviceName: "ITR Filing for LLP",
    period: fy24Period,
    status: "information_pending",
    priority: "medium",
    assignedUserId: IDS.USERS.SENIOR_1,
    assignedTeamId: IDS.TEAMS.TAXATION,
    supervisingPartnerId: IDS.USERS.PARTNER_1,
    dueDate: "2024-10-31",
    estimatedHours: 25,
    actualHours: 5,
    progress: 20,
    stage: "information_pending",
    stageHistory: createStageHistory([
      { stage: "created", date: "2024-04-15T10:00:00Z", by: IDS.USERS.ADMIN },
      {
        stage: "information_pending",
        date: "2024-04-20T10:00:00Z",
        by: IDS.USERS.SENIOR_1,
        notes: "Awaiting profit & loss statement",
      },
    ]),
    billingMethod: "fixed_fee",
    budgetAmount: 35000,
    billedAmount: 0,
    tags: ["itr", "llp", "fy24"],
    isBillable: true,
    complianceCycleId: IDS.COMPLIANCE_CYCLES.XYZ_ITR_FY24,
  },
  {
    ...baseEntity,
    id: IDS.MATTERS.XYZ_GST_MONTHLY,
    matterNumber: "MTR-XYZ-GST-24-001",
    name: "XYZ LLP - GST April 2024",
    description: "GSTR-1 (quarterly) and GSTR-3B (monthly) for April 2024 under QRMP",
    clientId: IDS.CLIENTS.XYZ_LLP,
    serviceType: "gst_quarterly",
    serviceName: "GST Quarterly Return (QRMP)",
    period: aprPeriod,
    status: "completed",
    priority: "medium",
    assignedUserId: IDS.USERS.ASSOCIATE_1,
    assignedTeamId: IDS.TEAMS.GST,
    supervisingPartnerId: IDS.USERS.PARTNER_1,
    dueDate: "2024-05-13",
    estimatedHours: 6,
    actualHours: 5,
    progress: 100,
    stage: "completed",
    stageHistory: createStageHistory([
      { stage: "created", date: "2024-04-01T10:00:00Z", by: IDS.USERS.ADMIN },
      { stage: "in_progress", date: "2024-05-01T10:00:00Z", by: IDS.USERS.ASSOCIATE_1 },
      { stage: "ready_for_review", date: "2024-05-10T10:00:00Z", by: IDS.USERS.ASSOCIATE_1 },
      { stage: "approved", date: "2024-05-11T10:00:00Z", by: IDS.USERS.PARTNER_1 },
      { stage: "filed", date: "2024-05-12T10:00:00Z", by: IDS.USERS.ASSOCIATE_1 },
      { stage: "completed", date: "2024-05-12T10:00:00Z", by: IDS.USERS.ASSOCIATE_1 },
    ]),
    billingMethod: "fixed_fee",
    budgetAmount: 10000,
    billedAmount: 10000,
    tags: ["gst", "qrmp", "apr", "completed"],
    isBillable: true,
    complianceCycleId: IDS.COMPLIANCE_CYCLES.XYZ_GST_APR,
  },
  {
    ...baseEntity,
    id: IDS.MATTERS.SHARMA_ITR_FY24,
    matterNumber: "MTR-SHA-ITR-24-001",
    name: "Sharma & Associates - ITR FY 2024-25",
    description: "ITR-3 filing for proprietorship business",
    clientId: IDS.CLIENTS.SHARMA_PROP,
    serviceType: "itr",
    serviceName: "ITR Filing for Proprietorship",
    period: fy24Period,
    status: "created",
    priority: "low",
    assignedUserId: IDS.USERS.ASSOCIATE_1,
    assignedTeamId: IDS.TEAMS.TAXATION,
    supervisingPartnerId: IDS.USERS.MANAGER_1,
    dueDate: "2024-07-31",
    estimatedHours: 10,
    actualHours: 0,
    progress: 0,
    stage: "created",
    stageHistory: createStageHistory([{ stage: "created", date: "2024-04-20T10:00:00Z", by: IDS.USERS.ADMIN }]),
    billingMethod: "fixed_fee",
    budgetAmount: 15000,
    billedAmount: 0,
    tags: ["itr", "proprietorship", "fy24"],
    isBillable: true,
    complianceCycleId: IDS.COMPLIANCE_CYCLES.SHARMA_ITR_FY24,
  },
  {
    ...baseEntity,
    id: IDS.MATTERS.GLOBAL_ITR_FY24,
    matterNumber: "MTR-GLB-ITR-24-001",
    name: "Global Corp India - ITR FY 2024-25",
    description: "Annual ITR filing with transfer pricing documentation",
    clientId: IDS.CLIENTS.GLOBAL_CORP,
    serviceType: "itr",
    serviceName: "ITR Filing",
    period: fy24Period,
    status: "in_progress",
    priority: "critical",
    assignedUserId: IDS.USERS.SENIOR_2,
    assignedTeamId: IDS.TEAMS.TAXATION,
    supervisingPartnerId: IDS.USERS.PARTNER_2,
    dueDate: "2024-10-31",
    estimatedHours: 60,
    actualHours: 35,
    progress: 58,
    stage: "in_progress",
    stageHistory: createStageHistory([
      { stage: "created", date: "2024-04-01T10:00:00Z", by: IDS.USERS.ADMIN },
      { stage: "information_pending", date: "2024-04-10T10:00:00Z", by: IDS.USERS.SENIOR_2 },
      {
        stage: "in_progress",
        date: "2024-05-01T10:00:00Z",
        by: IDS.USERS.SENIOR_2,
        notes: "TP documentation in progress",
      },
    ]),
    billingMethod: "fixed_fee",
    budgetAmount: 75000,
    billedAmount: 0,
    tags: ["itr", "transfer-pricing", "fy24", "critical"],
    isBillable: true,
    complianceCycleId: IDS.COMPLIANCE_CYCLES.GLOBAL_ITR_FY24,
  },
  {
    ...baseEntity,
    id: IDS.MATTERS.GLOBAL_GST_Q1,
    matterNumber: "MTR-GLB-GST-24-001",
    name: "Global Corp India - GST Q1 2024-25",
    description: "Monthly GST returns for April-June 2024",
    clientId: IDS.CLIENTS.GLOBAL_CORP,
    serviceType: "gst_monthly",
    serviceName: "GST Monthly Filing",
    period: q1Period,
    status: "in_progress",
    priority: "high",
    assignedUserId: IDS.USERS.SENIOR_2,
    assignedTeamId: IDS.TEAMS.GST,
    supervisingPartnerId: IDS.USERS.PARTNER_2,
    dueDate: "2024-07-11",
    estimatedHours: 18,
    actualHours: 12,
    progress: 67,
    stage: "in_progress",
    stageHistory: createStageHistory([
      { stage: "created", date: "2024-04-01T10:00:00Z", by: IDS.USERS.ADMIN },
      { stage: "in_progress", date: "2024-06-20T10:00:00Z", by: IDS.USERS.SENIOR_2 },
    ]),
    billingMethod: "fixed_fee",
    budgetAmount: 75000,
    billedAmount: 0,
    tags: ["gst", "q1", "monthly"],
    isBillable: true,
    complianceCycleId: IDS.COMPLIANCE_CYCLES.GLOBAL_GST_APR,
  },
  {
    ...baseEntity,
    id: IDS.MATTERS.GLOBAL_TDS_Q1,
    matterNumber: "MTR-GLB-TDS-24-001",
    name: "Global Corp India - TDS Q1 2024-25 (26Q)",
    description: "Quarterly TDS Return Form 26Q for non-salary payments",
    clientId: IDS.CLIENTS.GLOBAL_CORP,
    serviceType: "tds_26q",
    serviceName: "TDS Non-Salary (26Q)",
    period: q1Period,
    status: "ready_for_review",
    priority: "medium",
    assignedUserId: IDS.USERS.ASSOCIATE_2,
    assignedTeamId: IDS.TEAMS.TAXATION,
    supervisingPartnerId: IDS.USERS.PARTNER_2,
    dueDate: "2024-07-31",
    estimatedHours: 10,
    actualHours: 8,
    progress: 80,
    stage: "ready_for_review",
    stageHistory: createStageHistory([
      { stage: "created", date: "2024-04-01T10:00:00Z", by: IDS.USERS.ADMIN },
      { stage: "in_progress", date: "2024-07-01T10:00:00Z", by: IDS.USERS.ASSOCIATE_2 },
      { stage: "ready_for_review", date: "2024-07-15T10:00:00Z", by: IDS.USERS.ASSOCIATE_2 },
    ]),
    billingMethod: "fixed_fee",
    budgetAmount: 12000,
    billedAmount: 0,
    tags: ["tds", "26q", "q1"],
    isBillable: true,
    complianceCycleId: IDS.COMPLIANCE_CYCLES.GLOBAL_TDS_Q1,
  },
  {
    ...baseEntity,
    id: IDS.MATTERS.TECH_ITR_FY24,
    matterNumber: "MTR-TECH-ITR-24-001",
    name: "TechNova Solutions - ITR FY 2024-25",
    description: "ITR filing for SaaS startup with export income",
    clientId: IDS.CLIENTS.TECH_STARTUP,
    serviceType: "itr",
    serviceName: "ITR Filing",
    period: fy24Period,
    status: "information_pending",
    priority: "medium",
    assignedUserId: IDS.USERS.SENIOR_2,
    assignedTeamId: IDS.TEAMS.TAXATION,
    supervisingPartnerId: IDS.USERS.MANAGER_1,
    dueDate: "2024-10-31",
    estimatedHours: 30,
    actualHours: 8,
    progress: 27,
    stage: "information_pending",
    stageHistory: createStageHistory([
      { stage: "created", date: "2024-04-15T10:00:00Z", by: IDS.USERS.ADMIN },
      {
        stage: "information_pending",
        date: "2024-04-25T10:00:00Z",
        by: IDS.USERS.SENIOR_2,
        notes: "Awaiting audited financials",
      },
    ]),
    billingMethod: "fixed_fee",
    budgetAmount: 30000,
    billedAmount: 0,
    tags: ["itr", "startup", "export", "fy24"],
    isBillable: true,
    complianceCycleId: IDS.COMPLIANCE_CYCLES.TECH_ITR_FY24,
  },
  {
    ...baseEntity,
    id: IDS.MATTERS.TECH_GST_Q1,
    matterNumber: "MTR-TECH-GST-24-001",
    name: "TechNova Solutions - GST Q1 2024-25",
    description: "Monthly GST returns for April-June 2024",
    clientId: IDS.CLIENTS.TECH_STARTUP,
    serviceType: "gst_monthly",
    serviceName: "GST Monthly Filing",
    period: q1Period,
    status: "documents_pending",
    priority: "medium",
    assignedUserId: IDS.USERS.ASSOCIATE_2,
    assignedTeamId: IDS.TEAMS.GST,
    supervisingPartnerId: IDS.USERS.MANAGER_1,
    dueDate: "2024-07-11",
    estimatedHours: 8,
    actualHours: 1,
    progress: 12,
    stage: "documents_pending",
    stageHistory: createStageHistory([
      { stage: "created", date: "2024-04-01T10:00:00Z", by: IDS.USERS.ADMIN },
      { stage: "documents_pending", date: "2024-04-10T10:00:00Z", by: IDS.USERS.ASSOCIATE_2 },
    ]),
    billingMethod: "fixed_fee",
    budgetAmount: 36000,
    billedAmount: 0,
    tags: ["gst", "q1", "monthly"],
    isBillable: true,
    complianceCycleId: IDS.COMPLIANCE_CYCLES.TECH_GST_APR,
  },
  {
    ...baseEntity,
    id: IDS.MATTERS.RETAIL_ITR_FY24,
    matterNumber: "MTR-RTL-ITR-24-001",
    name: "RetailMax Chain - ITR FY 2024-25",
    description: "Annual ITR filing for multi-state retail chain",
    clientId: IDS.CLIENTS.RETAIL_CHAIN,
    serviceType: "itr",
    serviceName: "ITR Filing",
    period: fy24Period,
    status: "in_progress",
    priority: "high",
    assignedUserId: IDS.USERS.SENIOR_1,
    assignedTeamId: IDS.TEAMS.TAXATION,
    supervisingPartnerId: IDS.USERS.PARTNER_1,
    dueDate: "2024-10-31",
    estimatedHours: 50,
    actualHours: 28,
    progress: 56,
    stage: "in_progress",
    stageHistory: createStageHistory([
      { stage: "created", date: "2024-04-01T10:00:00Z", by: IDS.USERS.ADMIN },
      { stage: "in_progress", date: "2024-05-15T10:00:00Z", by: IDS.USERS.SENIOR_1 },
    ]),
    billingMethod: "fixed_fee",
    budgetAmount: 60000,
    billedAmount: 0,
    tags: ["itr", "retail", "multi-state", "fy24"],
    isBillable: true,
    complianceCycleId: IDS.COMPLIANCE_CYCLES.RETAIL_ITR_FY24,
  },
  {
    ...baseEntity,
    id: IDS.MATTERS.RETAIL_GST_Q1,
    matterNumber: "MTR-RTL-GST-24-001",
    name: "RetailMax Chain - GST Q1 2024-25",
    description: "Multi-state GST returns for April-June 2024",
    clientId: IDS.CLIENTS.RETAIL_CHAIN,
    serviceType: "gst_monthly",
    serviceName: "GST Monthly Filing (Multi-state)",
    period: q1Period,
    status: "overdue",
    priority: "urgent",
    assignedUserId: IDS.USERS.SENIOR_1,
    assignedTeamId: IDS.TEAMS.GST,
    supervisingPartnerId: IDS.USERS.PARTNER_1,
    dueDate: "2024-07-11",
    estimatedHours: 25,
    actualHours: 5,
    progress: 20,
    stage: "documents_pending",
    stageHistory: createStageHistory([
      { stage: "created", date: "2024-04-01T10:00:00Z", by: IDS.USERS.ADMIN },
      {
        stage: "documents_pending",
        date: "2024-04-05T10:00:00Z",
        by: IDS.USERS.SENIOR_1,
        notes: "Missing invoices from 3 states",
      },
    ]),
    billingMethod: "fixed_fee",
    budgetAmount: 90000,
    billedAmount: 0,
    tags: ["gst", "multi-state", "overdue", "urgent"],
    isBillable: true,
    complianceCycleId: IDS.COMPLIANCE_CYCLES.RETAIL_GST_APR,
  },
  {
    ...baseEntity,
    id: IDS.MATTERS.MFG_ITR_FY24,
    matterNumber: "MTR-MFG-ITR-24-001",
    name: "Precision Mfg Co - ITR FY 2024-25",
    description: "Annual ITR filing for export-oriented manufacturer",
    clientId: IDS.CLIENTS.MANUFACTURING_CO,
    serviceType: "itr",
    serviceName: "ITR Filing",
    period: fy24Period,
    status: "in_progress",
    priority: "high",
    assignedUserId: IDS.USERS.SENIOR_2,
    assignedTeamId: IDS.TEAMS.TAXATION,
    supervisingPartnerId: IDS.USERS.PARTNER_2,
    dueDate: "2024-10-31",
    estimatedHours: 45,
    actualHours: 25,
    progress: 56,
    stage: "in_progress",
    stageHistory: createStageHistory([
      { stage: "created", date: "2024-04-01T10:00:00Z", by: IDS.USERS.ADMIN },
      { stage: "in_progress", date: "2024-05-01T10:00:00Z", by: IDS.USERS.SENIOR_2 },
    ]),
    billingMethod: "fixed_fee",
    budgetAmount: 55000,
    billedAmount: 0,
    tags: ["itr", "manufacturing", "export", "fy24"],
    isBillable: true,
    complianceCycleId: IDS.COMPLIANCE_CYCLES.MFG_ITR_FY24,
  },
  {
    ...baseEntity,
    id: IDS.MATTERS.MFG_GST_Q1,
    matterNumber: "MTR-MFG-GST-24-001",
    name: "Precision Mfg Co - GST Q1 2024-25",
    description: "Monthly GST returns for April-June 2024",
    clientId: IDS.CLIENTS.MANUFACTURING_CO,
    serviceType: "gst_monthly",
    serviceName: "GST Monthly Filing",
    period: q1Period,
    status: "ready_for_review",
    priority: "high",
    assignedUserId: IDS.USERS.ASSOCIATE_2,
    assignedTeamId: IDS.TEAMS.GST,
    supervisingPartnerId: IDS.USERS.PARTNER_2,
    dueDate: "2024-07-11",
    estimatedHours: 15,
    actualHours: 13,
    progress: 87,
    stage: "ready_for_review",
    stageHistory: createStageHistory([
      { stage: "created", date: "2024-04-01T10:00:00Z", by: IDS.USERS.ADMIN },
      { stage: "in_progress", date: "2024-06-25T10:00:00Z", by: IDS.USERS.ASSOCIATE_2 },
      { stage: "ready_for_review", date: "2024-07-05T10:00:00Z", by: IDS.USERS.ASSOCIATE_2 },
    ]),
    billingMethod: "fixed_fee",
    budgetAmount: 60000,
    billedAmount: 0,
    tags: ["gst", "q1", "review-pending"],
    isBillable: true,
    complianceCycleId: IDS.COMPLIANCE_CYCLES.MFG_GST_APR,
  },
  {
    ...baseEntity,
    id: IDS.MATTERS.HEALTH_ITR_FY24,
    matterNumber: "MTR-HLT-ITR-24-001",
    name: "MediCare Hospitals - ITR FY 2024-25",
    description: "ITR filing for hospital chain (GST exempt)",
    clientId: IDS.CLIENTS.HEALTHCARE_PVT,
    serviceType: "itr",
    serviceName: "ITR Filing",
    period: fy24Period,
    status: "information_pending",
    priority: "medium",
    assignedUserId: IDS.USERS.SENIOR_2,
    assignedTeamId: IDS.TEAMS.TAXATION,
    supervisingPartnerId: IDS.USERS.PARTNER_2,
    dueDate: "2024-10-31",
    estimatedHours: 30,
    actualHours: 5,
    progress: 17,
    stage: "information_pending",
    stageHistory: createStageHistory([
      { stage: "created", date: "2024-04-15T10:00:00Z", by: IDS.USERS.ADMIN },
      { stage: "information_pending", date: "2024-04-20T10:00:00Z", by: IDS.USERS.SENIOR_2 },
    ]),
    billingMethod: "fixed_fee",
    budgetAmount: 45000,
    billedAmount: 0,
    tags: ["itr", "healthcare", "gst-exempt", "fy24"],
    isBillable: true,
    complianceCycleId: IDS.COMPLIANCE_CYCLES.HEALTH_ITR_FY24,
  },
  {
    ...baseEntity,
    id: IDS.MATTERS.FINTECH_ITR_FY24,
    matterNumber: "MTR-FIN-ITR-24-001",
    name: "FinServe Advisory - ITR FY 2024-25",
    description: "ITR-5 filing for advisory LLP",
    clientId: IDS.CLIENTS.FINTECH_LLP,
    serviceType: "itr",
    serviceName: "ITR Filing for LLP",
    period: fy24Period,
    status: "completed",
    priority: "medium",
    assignedUserId: IDS.USERS.SENIOR_2,
    assignedTeamId: IDS.TEAMS.TAXATION,
    supervisingPartnerId: IDS.USERS.MANAGER_1,
    dueDate: "2024-10-31",
    estimatedHours: 20,
    actualHours: 18,
    progress: 100,
    stage: "completed",
    stageHistory: createStageHistory([
      { stage: "created", date: "2024-04-15T10:00:00Z", by: IDS.USERS.ADMIN },
      { stage: "in_progress", date: "2024-06-01T10:00:00Z", by: IDS.USERS.SENIOR_2 },
      { stage: "ready_for_review", date: "2024-06-20T10:00:00Z", by: IDS.USERS.SENIOR_2 },
      { stage: "approved", date: "2024-06-25T10:00:00Z", by: IDS.USERS.MANAGER_1 },
      { stage: "filed", date: "2024-06-28T10:00:00Z", by: IDS.USERS.SENIOR_2 },
      { stage: "completed", date: "2024-06-28T10:00:00Z", by: IDS.USERS.SENIOR_2 },
    ]),
    billingMethod: "fixed_fee",
    budgetAmount: 40000,
    billedAmount: 40000,
    tags: ["itr", "llp", "advisory", "completed"],
    isBillable: true,
    complianceCycleId: IDS.COMPLIANCE_CYCLES.FINTECH_ITR_FY24,
  },
  {
    ...baseEntity,
    id: IDS.MATTERS.REAL_ITR_FY24,
    matterNumber: "MTR-REA-ITR-24-001",
    name: "UrbanSpace Developers - ITR FY 2024-25",
    description: "Annual ITR filing for real estate developer",
    clientId: IDS.CLIENTS.REAL_ESTATE,
    serviceType: "itr",
    serviceName: "ITR Filing",
    period: fy24Period,
    status: "in_progress",
    priority: "high",
    assignedUserId: IDS.USERS.SENIOR_1,
    assignedTeamId: IDS.TEAMS.TAXATION,
    supervisingPartnerId: IDS.USERS.PARTNER_1,
    dueDate: "2024-10-31",
    estimatedHours: 40,
    actualHours: 20,
    progress: 50,
    stage: "in_progress",
    stageHistory: createStageHistory([
      { stage: "created", date: "2024-04-15T10:00:00Z", by: IDS.USERS.ADMIN },
      { stage: "in_progress", date: "2024-05-20T10:00:00Z", by: IDS.USERS.SENIOR_1 },
    ]),
    billingMethod: "fixed_fee",
    budgetAmount: 50000,
    billedAmount: 0,
    tags: ["itr", "real-estate", "fy24"],
    isBillable: true,
    complianceCycleId: IDS.COMPLIANCE_CYCLES.REAL_ITR_FY24,
  },
];

const createSubtasks = (
  taskId: string,
  items: { title: string; status: TaskStatus; order: number; assignedUserId?: string }[],
): Subtask[] =>
  items.map((item) => ({
    ...baseEntity,
    id: `sub-${taskId}-${item.order}` as any,
    taskId: taskId as any,
    title: item.title,
    assignedUserId: (item.assignedUserId || IDS.USERS.ASSOCIATE_1) as any,
    status: item.status,
    order: item.order,
  }));

const createChecklistItems = (
  taskId: string,
  matterId: string,
  items: { title: string; isCompleted: boolean; isMandatory: boolean; order: number }[],
): ChecklistItem[] =>
  items.map((item) => ({
    ...baseEntity,
    id: `chk-${taskId}-${item.order}` as any,
    taskId: taskId as any,
    matterId: matterId as any,
    title: item.title,
    isCompleted: item.isCompleted,
    isMandatory: item.isMandatory,
    order: item.order,
  }));

export const mockTasks: Task[] = [
  {
    ...baseEntity,
    id: IDS.TASKS.ABC_ITR_COLLECT_DOCS,
    taskNumber: "TSK-ABC-ITR-001",
    title: "Collect Financial Statements & Supporting Documents",
    description:
      "Collect audited financial statements, Form 26AS, Form 16, bank statements, and investment proofs for ITR filing",
    matterId: IDS.MATTERS.ABC_ITR_FY24,
    clientId: IDS.CLIENTS.ABC_PVT_LTD,
    assignedUserId: IDS.USERS.SENIOR_1,
    assignedTeamId: IDS.TEAMS.TAXATION,
    createdById: IDS.USERS.PARTNER_1,
    priority: "high",
    status: "completed",
    dueDate: "2024-05-31",
    startDate: "2024-05-01",
    completedAt: "2024-05-28T10:00:00Z",
    estimatedHours: 8,
    actualHours: 6,
    progress: 100,
    dependencies: [],
    subtasks: createSubtasks(IDS.TASKS.ABC_ITR_COLLECT_DOCS, [
      { title: "Request financial statements from client", status: "completed", order: 1 },
      { title: "Download Form 26AS from TRACES", status: "completed", order: 2 },
      { title: "Collect Form 16 from client HR", status: "completed", order: 3 },
      { title: "Obtain bank statements for FY", status: "completed", order: 4 },
    ]),
    checklistItems: createChecklistItems(IDS.TASKS.ABC_ITR_COLLECT_DOCS, IDS.MATTERS.ABC_ITR_FY24, [
      { title: "Audited Balance Sheet & P&L", isCompleted: true, isMandatory: true, order: 1 },
      { title: "Form 26AS", isCompleted: true, isMandatory: true, order: 2 },
      { title: "Form 16/16A", isCompleted: true, isMandatory: true, order: 3 },
      { title: "Bank Statements", isCompleted: true, isMandatory: true, order: 4 },
      { title: "Investment Proofs (80C, 80D)", isCompleted: true, isMandatory: false, order: 5 },
    ]),
    sourceCommunicationId: IDS.COMMUNICATIONS.ABC_EMAIL_1,
    tags: ["document-collection", "itr"],
    isBillable: true,
  },
  {
    ...baseEntity,
    id: IDS.TASKS.ABC_ITR_COMPUTE,
    taskNumber: "TSK-ABC-ITR-002",
    title: "Compute Total Income & Tax Liability",
    description:
      "Compute total income under various heads, apply deductions, calculate tax liability including surcharge and cess",
    matterId: IDS.MATTERS.ABC_ITR_FY24,
    clientId: IDS.CLIENTS.ABC_PVT_LTD,
    assignedUserId: IDS.USERS.SENIOR_1,
    assignedTeamId: IDS.TEAMS.TAXATION,
    createdById: IDS.USERS.PARTNER_1,
    priority: "high",
    status: "in_progress",
    dueDate: "2024-07-15",
    startDate: "2024-06-01",
    estimatedHours: 16,
    actualHours: 10,
    progress: 62,
    dependencies: [{ taskId: IDS.TASKS.ABC_ITR_COLLECT_DOCS, type: "blocked_by" }],
    subtasks: createSubtasks(IDS.TASKS.ABC_ITR_COMPUTE, [
      { title: "Compute income from business/profession", status: "completed", order: 1 },
      { title: "Compute capital gains", status: "in_progress", order: 2 },
      { title: "Apply Chapter VI-A deductions", status: "todo", order: 3 },
      { title: "Calculate tax, surcharge, cess", status: "todo", order: 4 },
      { title: "Compute MAT/AMT if applicable", status: "todo", order: 5 },
    ]),
    checklistItems: createChecklistItems(IDS.TASKS.ABC_ITR_COMPUTE, IDS.MATTERS.ABC_ITR_FY24, [
      { title: "Business income computation", isCompleted: true, isMandatory: true, order: 1 },
      { title: "Capital gains computation", isCompleted: false, isMandatory: true, order: 2 },
      { title: "Chapter VI-A deductions", isCompleted: false, isMandatory: true, order: 3 },
      { title: "Tax calculation with surcharge/cess", isCompleted: false, isMandatory: true, order: 4 },
      { title: "MAT/AMT computation", isCompleted: false, isMandatory: true, order: 5 },
    ]),
    tags: ["computation", "itr"],
    isBillable: true,
  },
  {
    ...baseEntity,
    id: IDS.TASKS.ABC_ITR_REVIEW,
    taskNumber: "TSK-ABC-ITR-003",
    title: "Review & File ITR-6",
    description: "Partner review of computation, finalize ITR-6, generate JSON, and file on portal",
    matterId: IDS.MATTERS.ABC_ITR_FY24,
    clientId: IDS.CLIENTS.ABC_PVT_LTD,
    assignedUserId: IDS.USERS.PARTNER_1,
    assignedTeamId: IDS.TEAMS.TAXATION,
    createdById: IDS.USERS.PARTNER_1,
    priority: "high",
    status: "todo",
    dueDate: "2024-10-25",
    estimatedHours: 8,
    actualHours: 0,
    progress: 0,
    dependencies: [{ taskId: IDS.TASKS.ABC_ITR_COMPUTE, type: "blocked_by" }],
    subtasks: createSubtasks(IDS.TASKS.ABC_ITR_REVIEW, [
      { title: "Partner review of computation", status: "todo", order: 1 },
      { title: "Prepare ITR-6 JSON", status: "todo", order: 2 },
      { title: "File on income tax portal", status: "todo", order: 3 },
      { title: "E-verify using DSC", status: "todo", order: 4 },
      { title: "Send acknowledgment to client", status: "todo", order: 5 },
    ]),
    checklistItems: createChecklistItems(IDS.TASKS.ABC_ITR_REVIEW, IDS.MATTERS.ABC_ITR_FY24, [
      { title: "Partner review completed", isCompleted: false, isMandatory: true, order: 1 },
      { title: "ITR-6 JSON generated", isCompleted: false, isMandatory: true, order: 2 },
      { title: "Return filed successfully", isCompleted: false, isMandatory: true, order: 3 },
      { title: "E-verification completed", isCompleted: false, isMandatory: true, order: 4 },
      { title: "Acknowledgment sent to client", isCompleted: false, isMandatory: true, order: 5 },
    ]),
    tags: ["review", "filing", "itr"],
    isBillable: true,
  },
  {
    ...baseEntity,
    id: IDS.TASKS.ABC_GST_RECON,
    taskNumber: "TSK-ABC-GST-001",
    title: "GSTR-2A/2B Reconciliation for Q1",
    description:
      "Reconcile purchase register with GSTR-2A/2B, identify mismatches, communicate with vendors for rectification",
    matterId: IDS.MATTERS.ABC_GST_Q1,
    clientId: IDS.CLIENTS.ABC_PVT_LTD,
    assignedUserId: IDS.USERS.SENIOR_1,
    assignedTeamId: IDS.TEAMS.GST,
    createdById: IDS.USERS.PARTNER_1,
    priority: "high",
    status: "completed",
    dueDate: "2024-06-30",
    startDate: "2024-06-15",
    completedAt: "2024-07-03T10:00:00Z",
    estimatedHours: 6,
    actualHours: 5,
    progress: 100,
    dependencies: [],
    subtasks: createSubtasks(IDS.TASKS.ABC_GST_RECON, [
      { title: "Download GSTR-2A/2B for Apr-Jun", status: "completed", order: 1 },
      { title: "Compare with purchase register", status: "completed", order: 2 },
      { title: "Identify and categorize mismatches", status: "completed", order: 3 },
      { title: "Send mismatch communication to vendors", status: "completed", order: 4 },
    ]),
    checklistItems: createChecklistItems(IDS.TASKS.ABC_GST_RECON, IDS.MATTERS.ABC_GST_Q1, [
      { title: "GSTR-2A/2B downloaded", isCompleted: true, isMandatory: true, order: 1 },
      { title: "Reconciliation completed", isCompleted: true, isMandatory: true, order: 2 },
      { title: "Mismatches communicated", isCompleted: true, isMandatory: false, order: 3 },
    ]),
    tags: ["reconciliation", "gst"],
    isBillable: true,
  },
  {
    ...baseEntity,
    id: IDS.TASKS.ABC_GST_FILE,
    taskNumber: "TSK-ABC-GST-002",
    title: "File GSTR-1 & GSTR-3B for Q1",
    description: "Prepare and file GSTR-1 (quarterly) and GSTR-3B (monthly) for April-June 2024",
    matterId: IDS.MATTERS.ABC_GST_Q1,
    clientId: IDS.CLIENTS.ABC_PVT_LTD,
    assignedUserId: IDS.USERS.SENIOR_1,
    assignedTeamId: IDS.TEAMS.GST,
    createdById: IDS.USERS.PARTNER_1,
    priority: "high",
    status: "in_review",
    dueDate: "2024-07-11",
    startDate: "2024-07-01",
    estimatedHours: 4,
    actualHours: 3,
    progress: 75,
    dependencies: [{ taskId: IDS.TASKS.ABC_GST_RECON, type: "blocked_by" }],
    subtasks: createSubtasks(IDS.TASKS.ABC_GST_FILE, [
      { title: "Prepare GSTR-1 summary", status: "completed", order: 1 },
      { title: "Prepare GSTR-3B for Apr, May, Jun", status: "completed", order: 2 },
      { title: "File GSTR-1", status: "in_progress", order: 3 },
      { title: "File GSTR-3B for each month", status: "todo", order: 4 },
    ]),
    checklistItems: createChecklistItems(IDS.TASKS.ABC_GST_FILE, IDS.MATTERS.ABC_GST_Q1, [
      { title: "GSTR-1 filed", isCompleted: false, isMandatory: true, order: 1 },
      { title: "GSTR-3B April filed", isCompleted: false, isMandatory: true, order: 2 },
      { title: "GSTR-3B May filed", isCompleted: false, isMandatory: true, order: 3 },
      { title: "GSTR-3B June filed", isCompleted: false, isMandatory: true, order: 4 },
    ]),
    tags: ["filing", "gst"],
    isBillable: true,
  },
  {
    ...baseEntity,
    id: IDS.TASKS.ABC_TDS_CHALLAN,
    taskNumber: "TSK-ABC-TDS-001",
    title: "Verify TDS Challans & Prepare 24Q",
    description: "Verify all TDS challans for Q1, prepare salary details, and generate Form 24Q",
    matterId: IDS.MATTERS.ABC_TDS_Q1,
    clientId: IDS.CLIENTS.ABC_PVT_LTD,
    assignedUserId: IDS.USERS.ASSOCIATE_1,
    assignedTeamId: IDS.TEAMS.TAXATION,
    createdById: IDS.USERS.PARTNER_1,
    priority: "medium",
    status: "todo",
    dueDate: "2024-07-25",
    estimatedHours: 6,
    actualHours: 2,
    progress: 33,
    dependencies: [],
    subtasks: createSubtasks(IDS.TASKS.ABC_TDS_CHALLAN, [
      { title: "Download challans from TRACES", status: "in_progress", order: 1 },
      { title: "Verify challan amounts with books", status: "todo", order: 2 },
      { title: "Prepare salary annexure", status: "todo", order: 3 },
      { title: "Generate 24Q FVU file", status: "todo", order: 4 },
    ]),
    checklistItems: createChecklistItems(IDS.TASKS.ABC_TDS_CHALLAN, IDS.MATTERS.ABC_TDS_Q1, [
      { title: "Challans verified", isCompleted: false, isMandatory: true, order: 1 },
      { title: "Salary annexure prepared", isCompleted: false, isMandatory: true, order: 2 },
      { title: "24Q FVU generated", isCompleted: false, isMandatory: true, order: 3 },
      { title: "24Q filed on TIN", isCompleted: false, isMandatory: true, order: 4 },
    ]),
    tags: ["tds", "24q", "challan"],
    isBillable: true,
  },
  {
    ...baseEntity,
    id: IDS.TASKS.XYZ_ITR_COLLECT,
    taskNumber: "TSK-XYZ-ITR-001",
    title: "Collect LLP Financial Data",
    description: "Collect profit & loss, balance sheet, partner remuneration details, and capital account statements",
    matterId: IDS.MATTERS.XYZ_ITR_FY24,
    clientId: IDS.CLIENTS.XYZ_LLP,
    assignedUserId: IDS.USERS.SENIOR_1,
    assignedTeamId: IDS.TEAMS.TAXATION,
    createdById: IDS.USERS.PARTNER_1,
    priority: "medium",
    status: "in_progress",
    dueDate: "2024-06-30",
    startDate: "2024-06-01",
    estimatedHours: 6,
    actualHours: 3,
    progress: 50,
    dependencies: [],
    subtasks: createSubtasks(IDS.TASKS.XYZ_ITR_COLLECT, [
      { title: "Request P&L and Balance Sheet", status: "completed", order: 1 },
      { title: "Collect partner remuneration details", status: "in_progress", order: 2 },
      { title: "Obtain capital account statements", status: "todo", order: 3 },
    ]),
    checklistItems: createChecklistItems(IDS.TASKS.XYZ_ITR_COLLECT, IDS.MATTERS.XYZ_ITR_FY24, [
      { title: "P&L and Balance Sheet", isCompleted: true, isMandatory: true, order: 1 },
      { title: "Partner remuneration details", isCompleted: false, isMandatory: true, order: 2 },
      { title: "Capital account statements", isCompleted: false, isMandatory: true, order: 3 },
    ]),
    tags: ["document-collection", "itr", "llp"],
    isBillable: true,
  },
  {
    ...baseEntity,
    id: IDS.TASKS.GLOBAL_ITR_COMPUTE,
    taskNumber: "TSK-GLB-ITR-001",
    title: "Compute Income with Transfer Pricing",
    description: "Compute total income including transfer pricing adjustments, prepare TP documentation, Form 3CEB",
    matterId: IDS.MATTERS.GLOBAL_ITR_FY24,
    clientId: IDS.CLIENTS.GLOBAL_CORP,
    assignedUserId: IDS.USERS.SENIOR_2,
    assignedTeamId: IDS.TEAMS.TAXATION,
    createdById: IDS.USERS.PARTNER_2,
    priority: "critical",
    status: "in_progress",
    dueDate: "2024-08-31",
    startDate: "2024-05-15",
    estimatedHours: 30,
    actualHours: 22,
    progress: 73,
    dependencies: [],
    subtasks: createSubtasks(IDS.TASKS.GLOBAL_ITR_COMPUTE, [
      { title: "Benchmarking study for TP", status: "completed", order: 1, assignedUserId: IDS.USERS.ASSOCIATE_2 },
      { title: "Compute ALP for international transactions", status: "in_progress", order: 2 },
      { title: "Prepare Form 3CEB", status: "todo", order: 3 },
      { title: "Compute total income with TP adjustments", status: "todo", order: 4 },
    ]),
    checklistItems: createChecklistItems(IDS.TASKS.GLOBAL_ITR_COMPUTE, IDS.MATTERS.GLOBAL_ITR_FY24, [
      { title: "TP benchmarking study", isCompleted: true, isMandatory: true, order: 1 },
      { title: "ALP computation", isCompleted: false, isMandatory: true, order: 2 },
      { title: "Form 3CEB preparation", isCompleted: false, isMandatory: true, order: 3 },
      { title: "Total income computation", isCompleted: false, isMandatory: true, order: 4 },
    ]),
    tags: ["transfer-pricing", "computation", "itr", "critical"],
    isBillable: true,
  },
];

export const getMatterById = (id: string): Matter | undefined => mockMatters.find((m) => m.id === id);
export const getMattersByClient = (clientId: string): Matter[] => mockMatters.filter((m) => m.clientId === clientId);
export const getMattersByUser = (userId: string): Matter[] => mockMatters.filter((m) => m.assignedUserId === userId);
export const getMattersByTeam = (teamId: string): Matter[] => mockMatters.filter((m) => m.assignedTeamId === teamId);
export const getMattersByStatus = (status: MatterStatus): Matter[] => mockMatters.filter((m) => m.status === status);
export const getTasksByMatter = (matterId: string): Task[] => mockTasks.filter((t) => t.matterId === matterId);
export const getTasksByClient = (clientId: string): Task[] => mockTasks.filter((t) => t.clientId === clientId);
export const getTasksByUser = (userId: string): Task[] => mockTasks.filter((t) => t.assignedUserId === userId);
export const getTasksByStatus = (status: TaskStatus): Task[] => mockTasks.filter((t) => t.status === status);
export const getTaskById = (id: string): Task | undefined => mockTasks.find((t) => t.id === id);

export const getTasksByComplianceCycle = (complianceCycleId: string): Task[] => {
  const matterIds = mockMatters.filter((m) => m.complianceCycleId === complianceCycleId).map((m) => m.id);
  return mockTasks.filter((t) => t.matterId && matterIds.includes(t.matterId));
};

export const getTasksByConversation = (conversationId: string): Task[] => {
  const linkedTaskIds = mockCommunications
    .filter((c) => c.conversationId === conversationId && c.linkedTaskId)
    .map((c) => c.linkedTaskId!);
  return mockTasks.filter((t) => linkedTaskIds.includes(t.id));
};

export const getTasksByDocument = (documentId: string): Task[] => {
  const linkedTaskIds = mockCommunications
    .filter((c) => c.attachments.some((a) => a.documentId === documentId) && c.linkedTaskId)
    .map((c) => c.linkedTaskId!);
  return mockTasks.filter((t) => linkedTaskIds.includes(t.id));
};
