import type { Department, Permission, Team, User, UserRole } from "@/types";

import { IDS } from "./ids";

const now = new Date().toISOString();
const tenantId = IDS.TENANT;

export const mockPermissions: Permission[] = [
  { module: "clients", action: "view", scope: "all" },
  { module: "clients", action: "create", scope: "all" },
  { module: "clients", action: "edit", scope: "all" },
  { module: "clients", action: "delete", scope: "firm" },
  { module: "matters", action: "view", scope: "all" },
  { module: "matters", action: "create", scope: "all" },
  { module: "matters", action: "edit", scope: "all" },
  { module: "matters", action: "delete", scope: "firm" },
  { module: "tasks", action: "view", scope: "all" },
  { module: "tasks", action: "create", scope: "all" },
  { module: "tasks", action: "edit", scope: "all" },
  { module: "tasks", action: "delete", scope: "firm" },
  { module: "compliance", action: "view", scope: "all" },
  { module: "compliance", action: "create", scope: "all" },
  { module: "compliance", action: "edit", scope: "all" },
  { module: "documents", action: "view", scope: "all" },
  { module: "documents", action: "create", scope: "all" },
  { module: "documents", action: "edit", scope: "all" },
  { module: "communications", action: "view", scope: "all" },
  { module: "communications", action: "create", scope: "all" },
  { module: "billing", action: "view", scope: "all" },
  { module: "billing", action: "create", scope: "all" },
  { module: "billing", action: "financial", scope: "firm" },
  { module: "reports", action: "view", scope: "all" },
  { module: "administration", action: "view", scope: "firm" },
  { module: "administration", action: "admin", scope: "firm" },
];

const baseUser = {
  tenantId,
  createdAt: now,
  updatedAt: now,
  createdBy: IDS.USERS.ADMIN,
  updatedBy: IDS.USERS.ADMIN,
  mfaEnabled: true,
  timezone: "Asia/Kolkata",
  language: "en",
};

export const mockDepartments: Department[] = [
  {
    id: IDS.DEPARTMENTS.TAX,
    name: "Taxation",
    description: "Direct and indirect tax compliance and advisory",
    headId: IDS.USERS.PARTNER_1,
    teamIds: [IDS.TEAMS.TAXATION, IDS.TEAMS.GST],
    tenantId,
    createdAt: now,
    updatedAt: now,
    createdBy: IDS.USERS.ADMIN,
    updatedBy: IDS.USERS.ADMIN,
  },
  {
    id: IDS.DEPARTMENTS.AUDIT,
    name: "Audit & Assurance",
    description: "Statutory, tax, and internal audit engagements",
    headId: IDS.USERS.PARTNER_2,
    teamIds: [IDS.TEAMS.AUDIT],
    tenantId,
    createdAt: now,
    updatedAt: now,
    createdBy: IDS.USERS.ADMIN,
    updatedBy: IDS.USERS.ADMIN,
  },
  {
    id: IDS.DEPARTMENTS.ADVISORY,
    name: "Advisory Services",
    description: "Business advisory, transaction advisory, and consulting",
    headId: IDS.USERS.MANAGER_1,
    teamIds: [IDS.TEAMS.ADVISORY],
    tenantId,
    createdAt: now,
    updatedAt: now,
    createdBy: IDS.USERS.ADMIN,
    updatedBy: IDS.USERS.ADMIN,
  },
  {
    id: IDS.DEPARTMENTS.OPERATIONS,
    name: "Operations",
    description: "Secretarial, payroll, and back-office operations",
    headId: IDS.USERS.MANAGER_2,
    teamIds: [IDS.TEAMS.SECRETARIAL, IDS.TEAMS.PAYROLL],
    tenantId,
    createdAt: now,
    updatedAt: now,
    createdBy: IDS.USERS.ADMIN,
    updatedBy: IDS.USERS.ADMIN,
  },
];

export const mockTeams: Team[] = [
  {
    id: IDS.TEAMS.TAXATION,
    name: "Direct Taxation",
    description: "ITR, TDS, and tax planning",
    leadId: IDS.USERS.MANAGER_1,
    memberIds: [IDS.USERS.SENIOR_1, IDS.USERS.ASSOCIATE_1, IDS.USERS.ASSOCIATE_2],
    departmentId: IDS.DEPARTMENTS.TAX,
    specialization: ["itr", "tds_24q", "tds_26q", "tds_27q", "tds_27eq"],
    tenantId,
    createdAt: now,
    updatedAt: now,
    createdBy: IDS.USERS.ADMIN,
    updatedBy: IDS.USERS.ADMIN,
  },
  {
    id: IDS.TEAMS.GST,
    name: "GST Compliance",
    description: "GST returns, reconciliation, and advisory",
    leadId: IDS.USERS.SENIOR_1,
    memberIds: [IDS.USERS.ASSOCIATE_1, IDS.USERS.ASSOCIATE_2],
    departmentId: IDS.DEPARTMENTS.TAX,
    specialization: ["gst_monthly", "gst_quarterly", "gst_annual"],
    tenantId,
    createdAt: now,
    updatedAt: now,
    createdBy: IDS.USERS.ADMIN,
    updatedBy: IDS.USERS.ADMIN,
  },
  {
    id: IDS.TEAMS.AUDIT,
    name: "Audit Team",
    description: "Statutory and tax audit engagements",
    leadId: IDS.USERS.MANAGER_2,
    memberIds: [IDS.USERS.SENIOR_2, IDS.USERS.ASSOCIATE_1],
    departmentId: IDS.DEPARTMENTS.AUDIT,
    specialization: ["audit_statutory", "audit_tax", "audit_internal"],
    tenantId,
    createdAt: now,
    updatedAt: now,
    createdBy: IDS.USERS.ADMIN,
    updatedBy: IDS.USERS.ADMIN,
  },
  {
    id: IDS.TEAMS.ADVISORY,
    name: "Advisory Team",
    description: "Business and tax advisory services",
    leadId: IDS.USERS.MANAGER_1,
    memberIds: [IDS.USERS.SENIOR_2],
    departmentId: IDS.DEPARTMENTS.ADVISORY,
    specialization: ["advisory_tax", "advisory_gst", "advisory_corporate"],
    tenantId,
    createdAt: now,
    updatedAt: now,
    createdBy: IDS.USERS.ADMIN,
    updatedBy: IDS.USERS.ADMIN,
  },
  {
    id: IDS.TEAMS.SECRETARIAL,
    name: "Secretarial Compliance",
    description: "MCA/ROC filings and corporate secretarial",
    leadId: IDS.USERS.SENIOR_1,
    memberIds: [IDS.USERS.ASSOCIATE_2],
    departmentId: IDS.DEPARTMENTS.OPERATIONS,
    specialization: ["mca_aoc4", "mca_mgt7", "mca_adt1", "mca_dpt3"],
    tenantId,
    createdAt: now,
    updatedAt: now,
    createdBy: IDS.USERS.ADMIN,
    updatedBy: IDS.USERS.ADMIN,
  },
  {
    id: IDS.TEAMS.PAYROLL,
    name: "Payroll & HR",
    description: "Payroll processing and HR compliance",
    leadId: IDS.USERS.SUPPORT_1,
    memberIds: [],
    departmentId: IDS.DEPARTMENTS.OPERATIONS,
    specialization: ["payroll"],
    tenantId,
    createdAt: now,
    updatedAt: now,
    createdBy: IDS.USERS.ADMIN,
    updatedBy: IDS.USERS.ADMIN,
  },
];

const getUserTeams = (userId: string): Team[] =>
  mockTeams.filter((t) => t.memberIds.includes(userId as any) || t.leadId === userId);

export const mockUsers: User[] = [
  {
    ...baseUser,
    id: IDS.USERS.ADMIN,
    email: "admin@canexus.com",
    firstName: "Rajesh",
    lastName: "Kumar",
    fullName: "Rajesh Kumar",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=rajesh",
    phone: "+91-9876543210",
    role: "admin",
    teams: getUserTeams(IDS.USERS.ADMIN),
    department: mockDepartments[0],
    permissions: mockPermissions,
    isActive: true,
    lastLoginAt: now,
  },
  {
    ...baseUser,
    id: IDS.USERS.PARTNER_1,
    email: "partner1@canexus.com",
    firstName: "Priya",
    lastName: "Sharma",
    fullName: "Priya Sharma",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=priya",
    phone: "+91-9876543211",
    role: "partner",
    teams: getUserTeams(IDS.USERS.PARTNER_1),
    department: mockDepartments[0],
    permissions: mockPermissions.filter((p) => p.scope !== "firm" || p.action !== "admin"),
    isActive: true,
    lastLoginAt: now,
  },
  {
    ...baseUser,
    id: IDS.USERS.PARTNER_2,
    email: "partner2@canexus.com",
    firstName: "Amit",
    lastName: "Patel",
    fullName: "Amit Patel",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=amit",
    phone: "+91-9876543212",
    role: "partner",
    teams: getUserTeams(IDS.USERS.PARTNER_2),
    department: mockDepartments[1],
    permissions: mockPermissions.filter((p) => p.scope !== "firm" || p.action !== "admin"),
    isActive: true,
    lastLoginAt: now,
  },
  {
    ...baseUser,
    id: IDS.USERS.MANAGER_1,
    email: "manager1@canexus.com",
    firstName: "Neha",
    lastName: "Singh",
    fullName: "Neha Singh",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=neha",
    phone: "+91-9876543213",
    role: "manager",
    teams: getUserTeams(IDS.USERS.MANAGER_1),
    department: mockDepartments[0],
    permissions: mockPermissions.filter((p) => p.scope !== "firm"),
    isActive: true,
    lastLoginAt: now,
  },
  {
    ...baseUser,
    id: IDS.USERS.MANAGER_2,
    email: "manager2@canexus.com",
    firstName: "Vikram",
    lastName: "Mehta",
    fullName: "Vikram Mehta",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=vikram",
    phone: "+91-9876543214",
    role: "manager",
    teams: getUserTeams(IDS.USERS.MANAGER_2),
    department: mockDepartments[1],
    permissions: mockPermissions.filter((p) => p.scope !== "firm"),
    isActive: true,
    lastLoginAt: now,
  },
  {
    ...baseUser,
    id: IDS.USERS.SENIOR_1,
    email: "senior1@canexus.com",
    firstName: "Anjali",
    lastName: "Gupta",
    fullName: "Anjali Gupta",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=anjali",
    phone: "+91-9876543215",
    role: "senior_associate",
    teams: getUserTeams(IDS.USERS.SENIOR_1),
    department: mockDepartments[0],
    permissions: mockPermissions.filter((p) => p.scope === "own" || p.scope === "team"),
    isActive: true,
    lastLoginAt: now,
  },
  {
    ...baseUser,
    id: IDS.USERS.SENIOR_2,
    email: "senior2@canexus.com",
    firstName: "Rohit",
    lastName: "Agarwal",
    fullName: "Rohit Agarwal",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=rohit",
    phone: "+91-9876543216",
    role: "senior_associate",
    teams: getUserTeams(IDS.USERS.SENIOR_2),
    department: mockDepartments[1],
    permissions: mockPermissions.filter((p) => p.scope === "own" || p.scope === "team"),
    isActive: true,
    lastLoginAt: now,
  },
  {
    ...baseUser,
    id: IDS.USERS.ASSOCIATE_1,
    email: "associate1@canexus.com",
    firstName: "Kavya",
    lastName: "Nair",
    fullName: "Kavya Nair",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=kavya",
    phone: "+91-9876543217",
    role: "associate",
    teams: getUserTeams(IDS.USERS.ASSOCIATE_1),
    department: mockDepartments[0],
    permissions: mockPermissions.filter((p) => p.scope === "own"),
    isActive: true,
    lastLoginAt: now,
  },
  {
    ...baseUser,
    id: IDS.USERS.ASSOCIATE_2,
    email: "associate2@canexus.com",
    firstName: "Siddharth",
    lastName: "Reddy",
    fullName: "Siddharth Reddy",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=siddharth",
    phone: "+91-9876543218",
    role: "associate",
    teams: getUserTeams(IDS.USERS.ASSOCIATE_2),
    department: mockDepartments[0],
    permissions: mockPermissions.filter((p) => p.scope === "own"),
    isActive: true,
    lastLoginAt: now,
  },
  {
    ...baseUser,
    id: IDS.USERS.SUPPORT_1,
    email: "support@canexus.com",
    firstName: "Support",
    lastName: "Team",
    fullName: "Support Team",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=support",
    phone: "+91-9876543219",
    role: "support_staff",
    teams: getUserTeams(IDS.USERS.SUPPORT_1),
    department: mockDepartments[3],
    permissions: mockPermissions.filter((p) => p.scope === "own"),
    isActive: true,
    lastLoginAt: now,
  },
];

export const getUserById = (id: string): User | undefined => mockUsers.find((u) => u.id === id);
export const getTeamById = (id: string): Team | undefined => mockTeams.find((t) => t.id === id);
export const getUsersByTeam = (teamId: string): User[] => mockUsers.filter((u) => u.teams.some((t) => t.id === teamId));
export const getUsersByRole = (role: UserRole): User[] => mockUsers.filter((u) => u.role === role);
